### ISSUE TITLE
SLADE exhibits non-deterministic behavior when exporting assets

### ISSUE THREAD

**Issue by busybeaverhp** [sirjuddington/SLADE#1041] opened 2019-04-15 04:45 UTC
**SLADE Version**: 3.1.4
**Operating System**: Windows 10

**Issue Details**:
SLADE exhibits non-deterministic behavior when exporting assets

Example: exporting 500 PNG's doesn't always output 500, it's more like 490, 498... only 500 exported 25% of the time.
Something is causing SLADE to skip entries when exporting.
![image](https://user-images.githubusercontent.com/23037996/56107983-18a9dc00-5efe-11e9-9b3c-3a5e0c028f90.png)

**Comment by sirjuddington** [comment] 2019-05-03 03:30
Hmm I can't reproduce this one, are there any messages in the console log when it happens?

**Comment by sirjuddington** [comment] 2019-11-04 21:17
Closing this, feel free to reopen if it still happens

**Closed by sirjuddington** 2019-11-04 21:17 UTC
Labels: awaiting info, bug, resource editor
