### ISSUE TITLE
Compiling and installing with Homebrew on OSX: 

### ISSUE THREAD

**Issue by bramn** [sirjuddington/SLADE#443] opened 2016-01-29 08:08 UTC
Hello all, I wanted to start working on this nice guide about Doom level building: http://eev.ee/blog/2015/12/19/you-should-make-a-doom-level-part-1/

However I kept running into the issue where SLADE crashes when opening the line properties to edit its special, as described here: https://github.com/sirjuddington/SLADE/issues/366

Since it is supposed to be fixed, my next step was trying to compile and install SLADE with Homebrew, as described here: http://slade.mancubus.net/index.php?page=wiki&wikipage=Installation-on-OS-X-using-Homebrew

So far so good. Until however, Homebrew stopped installing and returned an error. Now I am stuck :(
This is the error I am receiving:

```
./src/generic/colrdlgg.cpp:524:41: error: use of undeclared identifier 'wxSystemSettings'
  wxPen pen(draw ? *wxBLACK_PEN : wxPen(wxSystemSettings::GetColour(wxSYS_COLOUR_3DFACE)));
                                        ^

./src/generic/colrdlgg.cpp:524:69: error: use of undeclared identifier 'wxSYS_COLOUR_3DFACE'
  wxPen pen(draw ? *wxBLACK_PEN : wxPen(wxSystemSettings::GetColour(wxSYS_COLOUR_3DFACE)));
                                                                    ^

2 errors generated.
make: *** [coredll_colrdlgg.o] Error 1
make: *** Waiting for unfinished jobs....
```

I _did_ notice the note for Homebrew users, but unlinking wxMac with _brew unlink wxmac_ does not help unfortunately. Any ideas?

**Comment by alexey-lysiuk** [comment] 2016-01-29 08:25
> However I kept running into the issue where SLADE crashes when opening the line properties to edit its special, as described here: #366

I think you are compiling the `master` branch but this issue was fixed in `3.1.1` only. Building with **Homebrew** won't help you as it uses `master` branch too.

Have no idea why you are getting the given error anyway. Can you try using [this method](https://github.com/alexey-lysiuk/slade-osx-build)?
By default it will use `master` branch. However if it will work for you there is a very simple way to switch to `3.1.1` after that.

**Comment by bramn** [comment] 2016-01-29 09:03
Are you sure issue #366 is fixed in 3.1.1 beta2 of SLADE? I tried it, but it kept crashing. Also, the bug report is dated after the release of 3.1.1 beta2. That is why I tried compiling the head master :)

Anyways, I tried compiling it your method and the build.sh script, unfortunately it also fails:

```
/Library/Frameworks/Mono.framework/Headers/ft2build.h:56:10: fatal error: 'freetype/config/ftheader.h' file not found
#include <freetype/config/ftheader.h>
         ^
```

**Comment by eevee** [comment] 2016-01-29 09:08
It's not fixed in 3.1.1 beta 2, but the `3.1.1` branch has further work on it after that.  `master` is a bit vestigial at the moment.

I wish I could help further (especially since I wrote the post you're trying to follow!), but I don't know much about building on OS X.  :(

Perhaps the 3.1.0 stable release will work for you?  Or you could try using the props panel to edit line properties, and avoid the dialog altogether.

**Comment by alexey-lysiuk** [comment] 2016-01-29 09:44
> /Library/Frameworks/Mono.framework/Headers/ft2build.h:56:10: fatal error: 'freetype/config/ftheader.h' file not found

For some reason CMake tries to use header files from installed **Mono.framework** ignoring include and library paths explicitly specified by the build script.
Honestly I'm out of ideas why this framework is being searched for headers. In other words, I need to have the same setup as on your OS X to figure out what's wrong.
I will install Mono and check by myself when I have time.

**Comment by bramn** [comment] 2016-01-29 15:24
I got it working! I removed the Mono framework for now and was able to build SLADE correctly. Could not remember what or whom was using Mono anyways.
Even though the resulting version is still 3.1.1 beta 2, it does not crash anymore when opening the line properties window. Guess the build number makes the difference?! :)

**Comment by sirjuddington** [comment] 2016-01-31 22:43
I only update version numbers when the version is released, so it will go up to beta 3 when that is released, etc. Could do it the other way, only problem is I sometimes don't know what the next version will actually be :P (could be beta, could be a full release)

Anyway this is resolved so closing the issue

**Closed by sirjuddington** 2016-01-31 22:43 UTC

**Comment by eGax** [comment] 2016-02-01 14:37
bramn nice to see someone doing a tutorial with Slade in mind.

**Comment by eevee** [comment] 2016-02-01 14:40
Should the Homebrew guide warn about this Mono problem, whatever it was?

**Comment by alexey-lysiuk** [comment] 2016-02-01 15:08
The problem is I have no idea what it was. At least I need to know how that Mono framework was installed: with some software or by dragging to Library folder. The exact framework version will help too. I suspect other system-wide changes, see no more reason for the search paths issue.
