### ISSUE TITLE
Slade corrupting files?

### ISSUE THREAD

**Issue by carbinedioxide** [sirjuddington/SLADE#340] opened 2015-10-30 01:29 UTC
Slade has been changing some of the files in my archives to pngs. Whether it's a newly made archive or an old downloaded archive, it has changed things from texts and sounds to pngs, decorates, textures, and markers. I talked to some people on Zdoom forums, and they have never experienced this. Any ideas of what to do?

**Comment by Gaerzi** [comment] 2015-10-30 02:31
Can you provide precise steps for replicating the issue?
- Exact files that end up replaced
- Exact version of SLADE you're using
- Step by step description of your process
- Your config file

**Comment by carbinedioxide** [comment] 2015-10-30 03:03
Oh yeah, sorry.

1. D_MUS01.ogg, D_MUS02.ogg, etc.
2. SLADE 3.1.0.5
3. I opened up SLADE, went to create new WAD file, compiled a text into ACS, imported ogg files, and saved it. later on, I made some changes regarding the ogg files, and saved again. I opened it back up and some of the music files ended up as either pngs, TEXTURES lumps, DECORATE lumps, or markers.
4. config file?

**Comment by carbinedioxide** [comment] 2016-04-23 18:45
This still happens to me, I might have to get a laptop if it's not resolved. 

The only thing I can do about it to cheat it is to Save As instead of Save. It won't corrupt or replace any files, but it is a waste of computer space having a bunch of almost the exact same copy of one PK3 file.

I can upload a bad file so you can see what I'm talking about.

**Comment by sirjuddington** [comment] 2016-06-28 05:09
Does this still happen with the latest version? It might be a duplicate of #477 which should be fixed now.

**Comment by sirjuddington** [comment] 2017-08-17 06:42
Closing - old issue, possibly fixed

Feel free to reopen the issue if needed

**Closed by sirjuddington** 2017-08-17 06:42 UTC
Labels: bug
