### ISSUE TITLE
SLADE crashes whenever I attempt to compile ACS.

### ISSUE THREAD

**Issue by DoomKrakken** [sirjuddington/SLADE#1435] opened 2022-11-11 21:09 UTC
I attempted to compile ACS in SLADE 3 and it keeps crashing whenever I do so.

ACS:
```
#library "JUMPPAD"
#include "zcommon.acs"
Script "Jump Pad" (void)
{
	If (GetActorZ(0) > 0.0)
	Delay (1);
	Else
	{
		ThrustThingZ(0, 100, 0, 0);
	}
}
```

Crash error:
```
Version: 3.2.1 (x86)
No current action

Operating System: Windows 7 (build 7601, Service Pack 1), 64-bit edition
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: (H:\Dev\SLADE\Build\src\Archive\ArchiveEntry.cpp:470) slade::ArchiveEntry::importFile
1: (H:\Dev\SLADE\Build\src\MainEditor\EntryOperations.cpp:1106) slade::entryoperations::compileACS
2: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:2666) slade::ArchivePanel::compileACS
3: (H:\Dev\SLADE\Build\src\MainEditor\UI\ArchivePanel.cpp:3390) slade::ArchivePanel::handleAction
4: (H:\Dev\SLADE\Build\src\General\SAction.cpp:466) slade::SActionHandler::doAction
5: (H:\Dev\SLADE\Build\src\UI\SToolBar\SToolBarButton.cpp:456) slade::SToolBarButton::onMouseEvent
6: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:655) wxAppConsoleBase::HandleEvent
7: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:666) wxAppConsoleBase::CallEventHandler
8: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1439) wxEvtHandler::ProcessEventIfMatchesId
9: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1901) wxEvtHandler::SearchDynamicEventTable
10: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\include\wx\event.h:4007) wxEvtHandler::TryBeforeAndHere
11: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1534) wxEvtHandler::ProcessEvent
12: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\event.cpp:1660) wxEvtHandler::SafelyProcessEvent
13: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:5967) wxWindow::HandleMouseEvent
14: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3185) wxWindow::MSWHandleMessage
15: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:3898) wxWindow::MSWWindowProc
16: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2940) wxWndProc
17: [unknown location] gapfnScSendMessage
18: [unknown location] GetThreadDesktop
19: [unknown location] CharPrevW
20: [unknown location] DispatchMessageW
21: [unknown location] IsDialogMessageW
22: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\window.cpp:2687) wxWindow::MSWProcessMessage
23: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:142) wxGUIEventLoop::PreProcessMessage
24: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:160) wxGUIEventLoop::ProcessMessage
25: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\evtloop.cpp:227) wxGUIEventLoop::Dispatch
26: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:239) wxEventLoopManual::ProcessEvents
27: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:288) wxEventLoopManual::DoRun
28: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\evtloopcmn.cpp:87) wxEventLoopBase::Run
29: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\appbase.cpp:377) wxAppConsoleBase::MainLoop
30: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\common\init.cpp:504) wxEntryReal
31: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:175) wxEntry
32: (H:\Dev\vcpkg\buildtrees\wxwidgets\src\a33b2c2a76-d63bc74efa.clean\src\msw\main.cpp:296) wxEntry
33: (H:\Dev\SLADE\Build\src\Application\SLADEWxApp.cpp:372) WinMain
34: (d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) __scrt_common_main_seh
35: [unknown location] BaseThreadInitThunk
36: [unknown location] RtlInitializeExceptionChain
37: [unknown location] RtlInitializeExceptionChain

Last Log Messages:

This is version 1.59 (Nov  9 2022)
This software is not supported by Raven Software or Activision
ZDoom changes and language extensions by Randy Heit
Further changes by Brad Carney
Even more changes by James Bentler
Some additions by Michael "Necromage" Weber
Error reporting improvements and limit expansion by Ty Halderman
Include paths added by Pascal vd Heiden
Error: File 'C:\Users\ByteBoi\AppData\Roaming\SLADE3\temp\JUMPPAD.acs' couldn't be removed (error 2: The system cannot find the file specified.)
```

**Comment by quotepilgrim** [comment] 2022-11-20 22:41
I've submitted a report for this issue a few months ago already, and it was added to the 3.2.2 milestone by the developer, so it should be fixed whenever that version is released. For the time being, there is a workaround I've been using. If you create an empty marker with the same name as your script inside the acs folder, with the .o extension instead of .acs, the script will compile successfully. So if your script is called "jumppad.acs", for instance, you should create a marker named "jumppad.o" in the acs directory, save, then compile.

**Comment by FlykeSpice** [comment] 2022-11-21 16:46
Please can you annex a sample wad where the crash is occuring?

**Comment by sirjuddington** [comment] 2022-11-27 04:57
Closing this as a duplicate of #1408

**Closed by sirjuddington** 2022-11-27 04:57 UTC
