### ISSUE TITLE
Slade crashes when trying to open any graphics file

### ISSUE THREAD

**Issue by Kzer-Za** [sirjuddington/SLADE#1219] opened 2020-11-28 09:52 UTC
**SLADE Version**: (3.2.0.b21)
**Operating System**: (Linux)

**Issue Details**:
Upon launching Slade from CLI there is this warning in the console:

```
12:39:01: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8).
```

Then, when I use "Open Directory" in Slade, there are these errors, though Slade does display the content of the directory:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

(slade:23313): Gdk-CRITICAL **: 12:39:40.012: gdk_window_peek_children: assertion 'GDK_IS_WINDOW (window)' failed

(slade:23313): Gdk-CRITICAL **: 12:39:40.013: gdk_window_peek_children: assertion 'GDK_IS_WINDOW (window)' failed
```

Then, when I select a graphics file (any of the png or jpg files that I have tried to open), Slade crashes and there are these lines in the console:

```
(slade:23479): Gdk-ERROR **: 12:42:46.630: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 36138 error_code 170 request_code 154 (GLX) minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  slade
```

System information:

Manjaro, x86_64, kernel 5.4, videocard: 512MB GeForce 9800 GT, non-free drivers.

**Comment by sirjuddington** [comment] 2020-12-11 02:29
This is a duplicate of #1027, closing (see the comments in that issue for a potential workaround)

**Closed by sirjuddington** 2020-12-11 02:29 UTC
