### ISSUE TITLE
Changing "Special" attribute on sector causes crash

### ISSUE THREAD

**Issue by ksnyder21** [sirjuddington/SLADE#1521] opened 2023-06-07 09:16 UTC
**SLADE Version**: (3.2.3) from DRD Team Package Repository.
**Operating System**: Kubuntu 23.04 x64

**Issue Details**:
Changing the "Special" attribute on a sector causes a crash.

Making a Doom 2 map with the GZDoom feature set.
Trying to set the "Special" attribute to 7 on a sector to make toxic goo.

If I set the Port to "None" when launching the editor, this issue does not occur.

Tried the "Boom" and "Eternity" Port options and the issue persists.

**Stack trace:**
Version: 3.2.3
No current action

Operating System: Linux 6.2.0-20-generic x86_64
Graphics Vendor: Intel
Graphics Hardware: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.0.2

Stack Trace:
0: [unknown location] wxLogger::DoLogWithNum(long, wchar_t const*, ...)
1: [unknown location] [unknown:140379920288120]
2: [unknown location] [unknown:140379873854640]
3: [unknown location] slade::SectorSpecialPanel::selectedSpecial() const
4: [unknown location] slade::MOPGSectorSpecialProperty::OnEvent(wxPropertyGrid*, wxWindow*, wxEvent&)
5: [unknown location] wxPropertyGrid::HandleCustomEditorEvent(wxEvent&)
6: [unknown location] wxPropertyGridEditorEventForwarder::ProcessEvent(wxEvent&)
7: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
8: [unknown location] wxButton::SetDefault()
9: [unknown location] g_signal_emit_valist
10: [unknown location] g_signal_emit
11: [unknown location] [unknown:140379891270752]
12: [unknown location] g_signal_emit_valist
13: [unknown location] g_signal_emit
14: [unknown location] [unknown:140379891270196]
15: [unknown location] [unknown:140379891015253]
16: [unknown location] g_signal_emit_valist
17: [unknown location] g_signal_emit
18: [unknown location] [unknown:140379892143886]
19: [unknown location] g_cclosure_marshal_VOID__BOXEDv
20: [unknown location] g_signal_emit_valist
21: [unknown location] g_signal_emit
22: [unknown location] [unknown:140379892108407]
23: [unknown location] [unknown:140379892141947]
24: [unknown location] [unknown:140379892145013]
25: [unknown location] gtk_event_controller_handle_event
26: [unknown location] [unknown:140379893807205]
27: [unknown location] [unknown:140379890997527]
28: [unknown location] g_closure_invoke
29: [unknown location] [unknown:140379887142149]
30: [unknown location] g_signal_emit_valist
31: [unknown location] g_signal_emit
32: [unknown location] [unknown:140379893868420]
33: [unknown location] [unknown:140379892444654]
34: [unknown location] gtk_main_do_event
35: [unknown location] [unknown:140379997984963]
36: [unknown location] [unknown:140379998337046]
37: [unknown location] g_main_context_dispatch
38: [unknown location] [unknown:140379886276984]
39: [unknown location] g_main_loop_run
40: [unknown location] gtk_main
41: [unknown location] wxGUIEventLoop::DoRun()
42: [unknown location] wxEventLoopBase::Run()
43: [unknown location] wxAppConsoleBase::OnRun()
44: [unknown location] wxEntry(int&, wchar_t**)
45: [unknown location] main
46: [unknown location] [unknown:140379873753744]
47: [unknown location] __libc_start_main
48: [unknown location] _start

Last Log Messages:
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map MAP01
Removed 79 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by sirjuddington** [comment] 2023-06-09 10:51
Closing as duplicate of #1512 (is fixed for the next version)

**Closed by sirjuddington** 2023-06-09 10:51 UTC
