### ISSUE TITLE
When raising several sectors at once it immediately crashed.

### ISSUE THREAD

**Issue by extremelygeneriusername** [sirjuddington/SLADE#1527] opened 2023-06-10 22:55 UTC
**SLADE Version**: 3.2.3 x64
**Operating System**: Windows

**Issue Details**:
Version: 3.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 10 (build 19045), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce GT 635/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 471.41

Stack Trace:
0: [unknown location] [unknown:3290009801]
1: [unknown location] [unknown:3290213208]
2: [unknown location] [unknown:3289726930]
3: [unknown location] [unknown:3289554605]
4: [unknown location] [unknown:3289700297]
5: [unknown location] [unknown:3284998740]
6: [unknown location] [unknown:3284301558]
7: [unknown location] [unknown:3293965492]
8: [unknown location] [unknown:3294130863]
9: [unknown location] [unknown:3294133763]
10: [unknown location] [unknown:3294134625]
11: [unknown location] [unknown:3294130650]
12: [unknown location] [unknown:3294134558]
13: [unknown location] [unknown:3295159459]
14: [unknown location] [unknown:3294130732]
15: [unknown location] [unknown:3294133610]
16: [unknown location] [unknown:3295657189]
17: [unknown location] [unknown:3295955545]
18: [unknown location] [unknown:3295186198]
19: [unknown location] [unknown:3296410287]
20: [unknown location] [unknown:3296412176]
21: [unknown location] [unknown:3295254229]
22: [unknown location] CallWindowProcW
23: [unknown location] DispatchMessageW
24: [unknown location] [unknown:3295175745]
25: [unknown location] [unknown:3295147942]
26: [unknown location] [unknown:3289729822]
27: [unknown location] [unknown:3289596464]
28: [unknown location] [unknown:3290054650]
29: [unknown location] [unknown:3293965492]
30: [unknown location] [unknown:3294130863]
31: [unknown location] [unknown:3294133763]
32: [unknown location] [unknown:3294134625]
33: [unknown location] [unknown:3294130650]
34: [unknown location] [unknown:3294133610]
35: [unknown location] [unknown:3295191971]
36: [unknown location] [unknown:3295218419]
37: [unknown location] [unknown:3295229064]
38: [unknown location] [unknown:3295254229]
39: [unknown location] CallWindowProcW
40: [unknown location] CallWindowProcW
41: [unknown location] glPushClientAttrib
42: [unknown location] CallWindowProcW
43: [unknown location] CallWindowProcW
44: [unknown location] [unknown:3293569569]
45: [unknown location] CallWindowProcW
46: [unknown location] DispatchMessageW
47: [unknown location] [unknown:3296560300]
48: [unknown location] [unknown:3294618115]
49: [unknown location] [unknown:3294618650]
50: [unknown location] [unknown:3293970967]
51: [unknown location] [unknown:3294656444]
52: [unknown location] [unknown:3294119560]
53: [unknown location] [unknown:3298950878]
54: [unknown location] BaseThreadInitThunk
55: [unknown location] RtlUserThreadStart

Last Log Messages:
Can't convert "lineid" to an integer (invalid)
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening map E1M1S1SC1
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by sirjuddington** [comment] 2023-06-21 07:34
Duplicate of #1512 (fixed for next release)

**Closed by sirjuddington** 2023-06-21 07:34 UTC
