### ISSUE TITLE
Texture editor does not display textures and additonally sometimes crashes.

### ISSUE THREAD

**Issue by artsy-computer-enjoyer** [sirjuddington/SLADE#1461] opened 2023-03-05 22:48 UTC
**SLADE Version**: (3.2.1)
**Operating System**: (Linux)

Description:
When opening the texture editor one of two things happens. Either it just crashes, or it opens but the textures are invisible. I tested this with Doom.wad and Doom2.wad, which I obtained legally through steam. Oddly enough this problem only happens with wads and not pk3s. I believe the problem has to do with "Failed to setup the OpenGL context." 

**Issue Details**:
Graphics Vendor: OpenGL not initialized
Graphics Hardware: OpenGL not initialized
OpenGL Version: OpenGL not initialized

Stack Trace:

Last Log Messages:
Error: can't open file '/home/emulation/.slade3/mainwindow.layout' (error 2: No such file or directory)
Tokenizer::openFile: Unable to open file /home/emulation/.slade3/mainwindow.layout
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/emulation/Desktop/DOOM2.WAD
Opening took 404 ms
Setting up the OpenGL context
Failed to setup the OpenGL context

**Comment by sirjuddington** [comment] 2023-06-04 13:53
This is a duplicate of #1390 (appears to be a wxWidgets/OpenGL issue)

**Closed by sirjuddington** 2023-06-04 13:53 UTC
Labels: linux, crash bug, texture editor
