### ISSUE TITLE
viewing graphical files stops rendering new frames

### ISSUE THREAD

**Issue by nemesis-vampy** [sirjuddington/SLADE#1703] opened 2024-07-29 18:05 UTC
### SLADE Version

3.2.6

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce and Observed Behavior

1. open an archive that has any file which appears graphically (image, playpal, map, etc)
2. click on the entry of the file, or do anything else that would cause it to be rendered
3. the window will stop rendering new frames, causing it to be stuck on the last frame before you opened the file.

actual functionality remains unchanged, but it's impossible to do anything without being able to see it.
opening the start page causes the window to start rendering again.
it only happens under wayland, running slade under xwayland will make it appear normally.

### Expected Behavior

slade should continue to render normally after opening graphical files.

### Screenshots

![image](https://github.com/user-attachments/assets/cfecb554-0c1c-466e-99c0-8b5a225420b9)

**Comment by Blzut3** [comment] 2024-07-30 23:06
Likely wxWidgets issue, See #1485 

Duplicate of #1351

**Closed by Blzut3** 2024-07-30 23:06 UTC
Labels: bug
