### ISSUE TITLE
Slade Crashes upon opening a map in the built in editor. It crashes with a backtrace when any map is open.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [sirjuddington/SLADE#1245] opened 2021-04-06 12:23 UTC
SLADE 3.2.0b2
Mageia Linux 8.

Slade Crashes opening a Hexen Mod. 
Slade Crashes upon opening a map in the built in editor. It crashes with a backtrace when any map is open.

If I can get a backtrace I will attach it to this bug.

Also, despite compiling from source and compiling Beta 2, Slade says it is compilng Beta 1 at run time.

**Comment by jwoodie** [comment] 2022-02-14 22:03
This also happens on SLADE 3.2.0b3 on Arch Linux.

I'm also running wayland I don't know if it doesn't happen on X11.

**Comment by FlykeSpice** [comment] 2022-05-14 14:53
I can't reproduce this on latest commits

**Comment by sirjuddington** [comment] 2023-05-23 02:41
Closing this as it's likely fixed (I can't reproduce and neither can the last commenter)

**Closed by sirjuddington** 2023-05-23 02:41 UTC
Labels: linux, crash bug, platform issue

**Comment by Zombie-Ryushu** [comment] 2023-05-23 02:47
I've not tried recently.
