### ISSUE TITLE
Feature Suggestion: User-definable UDMF prefab actions

### ISSUE THREAD

**Issue by jmickle66666666** [sirjuddington/SLADE#628] opened 2017-01-04 14:59 UTC
Suggested for GZDB on zdoom forums here: http://forum.zdoom.org/viewtopic.php?f=3&t=32392&p=967180#p967177

Setting up a config for "custom" actions, that sets default values for UDMF actions, for instance doors or lifts that have speeds set up, would greatly speed up mapping for zdoom. One advantage of boom/vanilla mapping is the speed that working with a limited set of actions provides. This speed can be provided in UDMF but with the advantages of the extra possible customisation if the user could define their own set of default line actions to select from, ideally in a sharable .cfg file

**Comment by Gaerzi** [comment] 2017-05-23 09:44
Duplicate of #721.

**Closed by Gaerzi** 2017-05-23 09:44 UTC
Labels: feature request, map editor
