### ISSUE TITLE
slade crashes after opening TEXTURES lump

### ISSUE THREAD

**Issue by Moth-Tolias** [sirjuddington/SLADE#1516] opened 2023-06-04 23:14 UTC
**SLADE Version**: v3.2.2
**Operating System**: Linux

**Issue Details**:
after generating a `TEXTURES` lump with Archive -> Texture Editor, and attempting to open the lump [whether by doubleclick or opening the texture editor again], slade hardcrashes with no error dialog.

this is the console output:
```
(slade:234589): Gdk-WARNING **: 00:04:37.220: The program 'slade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 54345 error_code 3 request_code 145 (unknown) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by sirjuddington** [comment] 2023-06-05 01:06
Closing this one as a duplicate of #1390

**Closed by sirjuddington** 2023-06-05 01:06 UTC
