### ISSUE TITLE
The longer SLADE is open, the worse the performance gets.

### ISSUE THREAD

**Issue by Phobos001** [sirjuddington/SLADE#1265] opened 2021-06-09 16:28 UTC
**SLADE Version**: v3.1.12
**Operating System**: Linux (Linux Mint/Ubuntu)

**Issue Details**:
After leaving the program/map editor open for long periods of time (a couple of hours), the performance begins to worsen. The longer the time, the worse the performance gets. Restarting SLADE fixes the issue, until enough time has passed again to be noticeably slow and janky, primarily in the 2D and 3D map editor views..

This mostly happens because I've been working on a level on and off throughout the days, coming back only to find the program is bogged down by some performance issues.

If you need more info please let me know.

**Comment by Gaerzi** [comment] 2021-06-09 19:24
Yes, this is an old problem, but we haven't been able to pinpoint the cause. It doesn't seem to affect Windows builds. Cf. #1016.

**Comment by sirjuddington** [comment] 2021-06-10 00:08
Closing this as it's a duplicate of #1016

**Closed by sirjuddington** 2021-06-10 00:08 UTC
