### ISSUE TITLE
Search Features

### ISSUE THREAD

**Issue by Catoptromancy** [sirjuddington/SLADE#696] opened 2017-03-13 04:00 UTC
SLADE Version: (3.1.2.alpha)
Operating System: (Linux) Debian 8.7

**Feature Request**
Slade should have the ability to search for tags, line and sector specials, thing types, line flags, maybe more stuff.

**Comment by sirjuddington** [comment] 2017-08-17 07:16
Duplicate of #157 

Also possible to do now (minus a UI) via scripting

**Closed by sirjuddington** 2017-08-17 07:16 UTC
