### ISSUE TITLE
3D Mode Camera is going crazy

### ISSUE THREAD

**Issue by DarkPulse** [sirjuddington/SLADE#891] opened 2018-06-24 19:28 UTC
**SLADE Version**: (3.1.2 Beta 5)
**Operating System**: (Windows 7 x64)

**Issue Details**:
Entering the 3D Mode Camera in SLADE's map editor causes the thing to go absolutely berserk, staring at either the floor or ceiling and spinning rapidly even with no input from me.

Searching the Closed Issues, I spotted this same issue for OSX (#676), but unfortunately, the fixes there seem to do nothing for me - I already had SLADE's EXE flagged to ignore the High DPI setting and it does nothing, and toggling it so it uses high DPI also does nothing. Not only that, but this build of SLADE is after this issue was resolved.

3D Camera mode is thus effectively useless.

**Comment by dpkonofa** [comment] 2018-07-27 01:04
Same issue for me. I think SLADE hasn't been updated in over a year so there's probably no fix but I'm having the exact same issue on a Mac.

**Comment by JadingTsunami** [comment] 2019-10-06 18:47
For Mac, try the instructions in #1048 

https://github.com/sirjuddington/SLADE/issues/1048#issuecomment-538775756

**Comment by sirjuddington** [comment] 2019-11-07 07:14
Closing this as a duplicate of #1048 (which has a workaround in the comments)

**Closed by sirjuddington** 2019-11-07 07:14 UTC
Labels: bug, map editor

**Comment by DarkPulse** [comment] 2019-11-08 04:46
That sort of workaround doesn't exist in Windows, so I'm not exactly sure how that would solve the issue.

Admittedly, I'm trying to see if it still exists, but now I can't even get SLADE to load "properly." It will start up alright, but the second I try to load a WAD, it simply hangs.

Gonna have to troubleshoot that at least, so will re-comment once I get that fixed.

**Comment by VonnegutNoise** [comment] 2023-10-26 07:33
hey! i don't normally write on forums but using this in 2023 and encountered the same issue-- for anyone coming from the internet who haven't been able to get the normal workarounds to work, changing the "camera_3d_sensitivity_x" and "camera_3d_sensitivity_y" variables in the "advanced settings" menu to 0.01 or similar makes the 3d mode a lot easier to use, no more spinning camera! 

with the white background on new macs bug, all the options might look blank but if you mouse over them you should be able to see them fine, they're pretty early in the list. arrow keys also work :)
