### ISSUE TITLE
Increasing slow down as a map is being worked on

### ISSUE THREAD

**Issue by inventor200** [sirjuddington/SLADE#1363] opened 2022-05-03 08:30 UTC
**SLADE Version**: 3.2.0
**Operating System**: Ubuntu 22.04

**Issue Details**:
So far, this only seems to be happening when I am compiling and testing ACS scripts for a GZDoom map, but something else may be happening to cause the slowdowns over time. It could be that the script editing is unrelated. While I'm editing a map, I'll open the script window, do some editing, compile the script, and test the map. I don't have hard data on this, but Slade seems to slow down faster if the script compilation has an error.

After less than ten compiles with some errors, visual mode begins to go to a crawl, and the whole program's UI gets slower and slower. If I close the map editor and reopen it, the slowness remains. I have to close Slade entirely to reset this. If scripting is unrelated, then in terms of total editing time, the slowdown starts to happen after editing for about an hour, but sometimes four hours. After a lot of ACS script bugfixing in a 30 minute period or so, the slowness returned, which is why I think it may be connected to whatever is calling the ACS compiler.

If you have tests for me to run, I'll write back to you here.

**Comment by sirjuddington** [comment] 2022-05-03 11:18
I think this is probably a duplicate of #1016, which has been around for a while and no one has been able to figure out what is going on. I personally haven't come across the issue, probably because I don't really use SLADE in linux other than for testing

**Comment by inventor200** [comment] 2022-05-03 13:44
Ah yeah, based on what other people have been posting there (if I put my superstitions aside), I think it's the same issue. Thank you for linking me in!

**Comment by sirjuddington** [comment] 2023-06-04 04:56
This issue should be fixed since 3.2.2

**Closed by sirjuddington** 2023-06-04 04:56 UTC
