### ISSUE TITLE
Blank message window on OSX prevents use of Slade3

### ISSUE THREAD

**Issue by PresidentPeople** [sirjuddington/SLADE#198] opened 2014-08-20 22:14 UTC
A blank space (left behind by the loading window?) appears in front of the Slade3 window, preventing any operation past First Time Setup.  

http://oi60.tinypic.com/w0729e.jpg

**Comment by sirjuddington** [comment] 2015-05-27 04:07
Fixed (duplicate of #262)

**Closed by sirjuddington** 2015-05-27 04:07 UTC
