### ISSUE TITLE
Texture editor crashes when opened

### ISSUE THREAD

**Issue by manito-manopla** [sirjuddington/SLADE#1564] opened 2023-09-07 23:07 UTC
**SLADE Version**: 3.2.3
**Operating System**: Debian 11 bullseye 
**Architecture**: x86 32 bit
**Issue Details**:
```
Version: 3.2.3
No current action

Operating System: Linux 5.10.0-25-686 i686
Graphics Vendor: Intel Open Source Technology Center
Graphics Hardware: Mesa DRI Intel(R) HD Graphics 2000 (SNB GT1)
OpenGL Version: 3.0 Mesa 20.3.5

Stack Trace:
0: [unknown location] wxLogger::DoLogWithNum(long, wchar_t const*, ...)
1: [unknown location] __kernel_sigreturn
2: [unknown location] [unknown:2699264782]
3: [unknown location] [unknown:2699257342]
4: [unknown location] [unknown:2699091376]
5: [unknown location] [unknown:2700418095]
6: [unknown location] slade::CTextureCanvas::draw()
7: [unknown location] slade::OGLCanvas::onPaint(wxPaintEvent&)
8: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
9: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
10: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
11: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
12: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
13: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
14: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
15: [unknown location] wxWindow::GTKSendPaintEvents(_cairo*)
16: [unknown location] wxGLCanvas::SetBackgroundStyle(wxBackgroundStyle)
17: [unknown location] [unknown:2983358999]
18: [unknown location] [unknown:2982980980]
19: [unknown location] g_closure_invoke
20: [unknown location] [unknown:2973367024]
21: [unknown location] g_signal_emit_valist
22: [unknown location] g_signal_emit
23: [unknown location] [unknown:2983037639]
24: [unknown location] gtk_container_propagate_draw
25: [unknown location] [unknown:2981171238]
26: [unknown location] [unknown:2983358999]
27: [unknown location] [unknown:2982980980]
28: [unknown location] g_closure_invoke
29: [unknown location] [unknown:2973365439]
30: [unknown location] g_signal_emit_valist
31: [unknown location] g_signal_emit
32: [unknown location] [unknown:2983037639]
33: [unknown location] gtk_container_propagate_draw
34: [unknown location] [unknown:2981171238]
35: [unknown location] [unknown:2983358999]
36: [unknown location] [unknown:2982980980]
37: [unknown location] g_closure_invoke
38: [unknown location] [unknown:2973365439]
39: [unknown location] g_signal_emit_valist
40: [unknown location] g_signal_emit
41: [unknown location] [unknown:2983037639]
42: [unknown location] gtk_container_propagate_draw
43: [unknown location] [unknown:2981737980]
44: [unknown location] [unknown:2980685285]
45: [unknown location] [unknown:2980708423]
46: [unknown location] [unknown:2980347255]
47: [unknown location] [unknown:2980708423]
48: [unknown location] [unknown:2981734124]
49: [unknown location] [unknown:2983037287]
50: [unknown location] gtk_container_propagate_draw
51: [unknown location] [unknown:2981171238]
52: [unknown location] [unknown:2983358999]
53: [unknown location] [unknown:2982980980]
54: [unknown location] g_closure_invoke
55: [unknown location] [unknown:2973365439]
56: [unknown location] g_signal_emit_valist
57: [unknown location] g_signal_emit
58: [unknown location] [unknown:2983037639]
59: [unknown location] gtk_container_propagate_draw
60: [unknown location] [unknown:2981171238]
61: [unknown location] [unknown:2983358999]
62: [unknown location] [unknown:2982980980]
63: [unknown location] g_closure_invoke
64: [unknown location] [unknown:2973365439]
65: [unknown location] g_signal_emit_valist
66: [unknown location] g_signal_emit
67: [unknown location] [unknown:2983037639]
68: [unknown location] gtk_container_propagate_draw
69: [unknown location] [unknown:2981171238]
70: [unknown location] [unknown:2983358999]
71: [unknown location] [unknown:2982980980]
72: [unknown location] g_closure_invoke
73: [unknown location] [unknown:2973365439]
74: [unknown location] g_signal_emit_valist
75: [unknown location] g_signal_emit
76: [unknown location] [unknown:2983037639]
77: [unknown location] gtk_container_propagate_draw
78: [unknown location] [unknown:2980662974]
79: [unknown location] [unknown:2980329838]
80: [unknown location] [unknown:2980685285]
81: [unknown location] [unknown:2980708423]
82: [unknown location] [unknown:2980340962]
83: [unknown location] [unknown:2983037287]
84: [unknown location] gtk_container_propagate_draw
85: [unknown location] [unknown:2980662974]
86: [unknown location] [unknown:2983095718]
87: [unknown location] [unknown:2983037287]
88: [unknown location] [unknown:2983074560]
89: [unknown location] gtk_main_do_event
90: [unknown location] [unknown:2978268855]
91: [unknown location] [unknown:2978345731]
92: [unknown location] [unknown:2978401116]
93: [unknown location] [unknown:2978353282]
94: [unknown location] [unknown:2978353799]
95: [unknown location] wxWindow::Update()
96: [unknown location] wxTabFrame::DoSizing()
97: [unknown location] wxTabFrame::DoSetSize(int, int, int, int, int)
98: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
99: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
100: [unknown location] wxSizer::Layout()
101: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
102: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
103: [unknown location] wxSizer::Layout()
104: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
105: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
106: [unknown location] wxSizer::Layout()
107: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
108: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
109: [unknown location] wxSizer::Layout()
110: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
111: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
112: [unknown location] wxSizer::Layout()
113: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
114: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
115: [unknown location] wxSizer::Layout()
116: [unknown location] wxWindowBase::Layout()
117: [unknown location] wxAuiManager::DoFrameLayout()
118: [unknown location] wxAuiManager::OnSize(wxSizeEvent&)
119: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
120: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
121: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
122: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
123: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
124: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
125: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
126: [unknown location] wxWindow::DoSetSize(int, int, int, int, int)
127: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
128: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
129: [unknown location] wxSizer::Layout()
130: [unknown location] wxWindowBase::Layout()
131: [unknown location] wxWindowBase::InternalOnSize(wxSizeEvent&)
132: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
133: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
134: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
135: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
136: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
137: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
138: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
139: [unknown location] wxWindow::DoSetSize(int, int, int, int, int)
140: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
141: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
142: [unknown location] wxSizer::Layout()
143: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
144: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
145: [unknown location] wxSizer::Layout()
146: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
147: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
148: [unknown location] wxSizer::Layout()
149: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
150: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
151: [unknown location] wxSizer::Layout()
152: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
153: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
154: [unknown location] wxSizer::Layout()
155: [unknown location] wxSizerItem::SetDimension(wxPoint const&, wxSize const&)
156: [unknown location] wxBoxSizer::RepositionChildren(wxSize const&)
157: [unknown location] wxSizer::Layout()
158: [unknown location] wxWindowBase::Layout()
159: [unknown location] wxTopLevelWindowBase::Layout()
160: [unknown location] wxAuiManager::DoFrameLayout()
161: [unknown location] wxAuiManager::OnSize(wxSizeEvent&)
162: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
163: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
164: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
165: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
166: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
167: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
168: [unknown location] wxWindowBase::HandleWindowEvent(wxEvent&) const
169: [unknown location] wxWindowBase::SendSizeEvent(int)
170: [unknown location] wxWindow::GTKSendSizeEventIfNeeded()
171: [unknown location] wxWindow::GTKSendSizeEventIfNeeded()
172: [unknown location] g_closure_invoke
173: [unknown location] [unknown:2973367553]
174: [unknown location] g_signal_emit_valist
175: [unknown location] g_signal_emit
176: [unknown location] [unknown:2978309520]
177: [unknown location] [unknown:2978313643]
178: [unknown location] [unknown:2978218124]
179: [unknown location] [unknown:2972197873]
180: [unknown location] g_main_context_dispatch
181: [unknown location] [unknown:2972195689]
182: [unknown location] g_main_loop_run
183: [unknown location] gtk_main
184: [unknown location] wxGUIEventLoop::DoRun()
185: [unknown location] wxEventLoopBase::Run()
186: [unknown location] wxAppConsoleBase::OnRun()
187: [unknown location] wxAppBase::OnRun()
188: [unknown location] wxEntry(int&, wchar_t**)
189: [unknown location] wxEntry(int&, char**)
190: [unknown location] main
191: [unknown location] __libc_start_main
192: [unknown location] _start

Last Log Messages:
Opening archive /home/manito/.wad/freedoom1.wad
Opening took 1985 ms
Setting up the OpenGL context
Initialising OpenGL...
OpenGL Version: 3.0
Max Texture Size: 8192x8192
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
```

**Comment by pbuyle** [comment] 2023-11-18 14:56
See https://github.com/sirjuddington/SLADE/issues/1390

**Comment by sirjuddington** [comment] 2023-12-02 05:52
Duplicate of #1390, not sure there is much I can do as it's a wxWidgets/linux issue

**Closed by sirjuddington** 2023-12-02 05:52 UTC
Labels: linux, crash bug
