### ISSUE TITLE
SLADE creates non-conformant zips

### ISSUE THREAD

**Issue by Kokokokoka** [sirjuddington/SLADE#1022] opened 2019-01-15 17:38 UTC
**Issue Details**:
multiple records with same file name are not allowed in well-formed zip file.
SLADE does the same for wads. 
And it only works for some of the source ports that use hacks (workarounds (f.e. 
load the first of the dup textures). Now you have to use (g)zdoom (or any other port with hacks) in order to play 
SLADE-created wads/zips/etc.

**Comment by sirjuddington** [comment] 2019-01-15 21:03
Yeah this should be done for 3.2.0 - it's a duplicate of #885 so closing this issue

**Closed by sirjuddington** 2019-01-15 21:03 UTC
