### ISSUE TITLE
[Feature Request] Support for MBF21 Spec for Map Editor

### ISSUE THREAD

**Issue by iainrm** [sirjuddington/SLADE#1470] opened 2023-04-01 17:30 UTC
**SLADE Version**: 3.2.2
**Operating System**: Any

**Issue Details**:
With the release of the new MBF21 spec, maps can now take advantage of several new linedef flags, linedef types, and sector effects. The full list of new features specifically for level editors is detailed here: https://github.com/kraflab/mbf21/blob/master/docs/level_editor_spec.md

While MBF21 as a spec is mostly an extension for DEHACKED, it would be very nice to have access to the full range of MBF21 tools in SLADE's map editor.

I've made a real dirty patch for my own personal use that gets me about 75% of the way there, that I'm including mostly for illustrative purposes. All of these files go in `SLADE.pk3`; `boom_mbf21.cfg` goes under `/config/ports` while the other .cfg files go under `/config/ports/include`.
[mbf21configs.zip](https://github.com/sirjuddington/SLADE/files/11130164/mbf21configs.zip)

The one big problem with this patch is that the new sector types are real kludge: they're generalized sector types which can't really be defined with these .cfg files and are instead hardcoded. For this reason I don't consider my patch to really be anything other than an example to show what this could maybe look like. It'd be better if someone smarter and cooler than me implemented this properly.

**Comment by sirjuddington** [comment] 2023-05-18 13:58
It's on the radar, closing this issue though, as it's a duplicate of #1396

**Closed by sirjuddington** 2023-05-18 13:58 UTC
Labels: feature support
