### ISSUE TITLE
Double-click to replace a patch in the texture list can generate bad X/Y positions

### ISSUE THREAD

**Issue by plumsinus** [sirjuddington/SLADE#178] opened 2014-07-01 06:39 UTC
Select any texture in the texture editor, select a patch in that texture, and then click on the "Replace selected patch(es)" button. Scroll the patch window by clicking & dragging the bar in the scrollbar. Then double-click a new patch to select it. The X and Y positions will change to be way outside the image.

**Comment by sirjuddington** [comment] 2019-11-07 06:37
Closing this issue since it's so old and I've never been able to reproduce it. Hopefully it was some kind of wx issue that is fixed now :P (the gif i noticed was linux, perhaps it's fixed with gtk3 now)

**Closed by sirjuddington** 2019-11-07 06:37 UTC
Labels: bug, resource editor
