### ISSUE TITLE
3D-Mode Camera always stuck pointing at either ceiling or floor and spinning rapidly.

### ISSUE THREAD

**Issue by Seachameleon** [sirjuddington/SLADE#676] opened 2017-03-01 15:59 UTC
**SLADE Version**: 3.1.1.5
**Operating System**: OSX

**Issue Details**:
I used SLADE previously for WAD compiling and construction, and it worked wonderfully for that purpose. Unable to find any good mapping tools compatible with OSX, I also began to use the map creation tool, which, aside from an at-times odd interface, worked flawlessly. 
Since then I've had my hard drive wiped for irrelevant reasons, and upon re-installing SLADE I quickly found that the camera in 3D mode of the map viewer will constantly spin in place rapidly, pointing either as far up or far down as possible. 

The only other issue to reference this I've found is #253

**Comment by fadookie** [comment] 2017-05-31 07:37
I am also getting this 100% of the time with latest stable build on macOS El Capitan.

**Comment by alexey-lysiuk** [comment] 2017-05-31 07:46
The issue is caused by Retina/HiDPI support in wxWidgets.
Unfortunately I have no vision how to fix this in a generic way, i.e. without some hackish workarounds.

**Comment by perfectionismtech** [comment] 2017-06-10 20:27
As a temporary workaround, open the app in low resolution mode (on Get Info).

**Comment by fadookie** [comment] 2017-06-12 17:21
@alexey-lysiuk @perfectionismtech Thank you, enabling low resolution mode fixed the issue!
Until there is a proper fix for this I'd suggest disabling retina support altogether by setting `NSHighResolutionCapable` to NO in `Info.plist` ... if I have time I'll make a PR.

**Comment by alexey-lysiuk** [comment] 2017-06-12 19:03
What's the point of disabling HiDPI support for everyone?
If user needs 3D view there is a workaround: set low resolution mode in bundle's properties.

**Comment by fadookie** [comment] 2017-06-13 02:13
The point would be so that new users don't have to trawl around github
trying to find said workaround when a whole edit mode is completely
unusable on most MacBook or iMacs made after 2012... if there are users on
mac who don't need this feature at the very least I think this should be
added prominently to the documentation.

**Comment by sirjuddington** [comment] 2017-08-17 23:49
Closing - should be fixed now

Feel free to reopen the issue if needed

**Closed by sirjuddington** 2017-08-17 23:49 UTC

**Comment by fadookie** [comment] 2025-06-12 14:57
On recent versions of macOS (I'm on Sequoia 15.4.1 with SLADE v3.2.5) the 3D camera is still almost impossible to control and spins wildly. The old workaround of setting low resolution mode doesn't seem to work, the checkbox for this is gone in Finder and I even tried editing the app's `Info.plist` and adding `NSHighResolutionCapable` = `NO` but this doesn't seem to have any effect.

I just tried [this workaround](https://github.com/sirjuddington/SLADE/issues/891#issuecomment-1780569137) and it seems to work somewhat OK though but it's still a bit unwieldy. I'm using a camera sensitivity value of `0.05` for now. I suggest we re-open this issue.
