### ISSUE TITLE
crash anomalo

### ISSUE THREAD

**Issue by piuzza127** [sirjuddington/SLADE#1712] opened 2024-08-18 12:04 UTC
### SLADE Version

3.2.6

### OS

Linux

### Editor

Map editor

### Steps to Reproduce

I was...

To reproduce:
4. Crash occurrs

### Crash Information

```text
Version: 3.2.6
No current action

Operating System: Linux 6.6.30-02726-gb84bbdf6955e x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Error: EGL version is 1.4. EGL version 1.5 or greater is required.
Error: can't open file '/home/matteobellini2014/.slade3/mapwindow.layout' (error 2: No such file or directory)
Tokenizer::openFile: Unable to open file /home/matteobellini2014/.slade3/mapwindow.layout
Setting up the OpenGL context
Failed to setup the OpenGL context
Opening map e1m1
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
```

### Screenshots

![DESCRIPTIO
![Screenshot 2024-08-18 14 02 35](https://github.com/user-attachments/assets/ae6503bc-69b1-47f6-a801-207490d9e8ba)
N](LINK.png)

**Comment by Blzut3** [comment] 2024-08-18 23:34
I assume this is a Chromebook.  What model is it?

**Comment by Blzut3** [comment] 2024-08-26 05:04
Duplicate of #1658.

**Closed by Blzut3** 2024-08-26 05:04 UTC
Labels: crash bug
