### ISSUE TITLE
Report port messages

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#792] opened 2017-09-17 10:34 UTC
See [this comment](https://forum.zdoom.org/viewtopic.php?p=1018682#p1018682).
> Likewise on Linux, GZDoom doesn't seem to show any startup window besides the IWAD selection. The only way to get the console output (including errors in mods) is to run from a terminal. Not a deal-breaker, but it is kind of annoying when I default to pressing "Run" in Slade and ... nothing happens because it failed silently.

While the thread in question is about GZDoom's lack of a GUI for these things on Linux, it would be a good idea for SLADE to collect the cout and cerr output of ports when running them. It could then be outputted to SLADE's own console, or optionally displayed in a messagebox.

**Comment by sirjuddington** [comment] 2022-03-28 10:26
This one is a duplicate of #425

**Closed by sirjuddington** 2022-03-28 10:26 UTC
Labels: enhancement
