### ISSUE TITLE
Slade keeps crashing when I try to create a map

### ISSUE THREAD

**Issue by pickleman64** [sirjuddington/SLADE#1707] opened 2024-08-10 23:02 UTC
### SLADE Version

3.2.6

### OS

Linux

### Editor

Map editor

### Steps to Reproduce

I was...

To reproduce:
4. Crash occurrs

### Crash Information

```text
Version: 3.2.6
No current action

Operating System: Linux 6.6.30-02726-gb84bbdf6955e x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Error: EGL version is 1.4. EGL version 1.5 or greater is required.
Error: can't open file '/home/salleykurt/.slade3/mapwindow.layout' (error 2: No such file or directory)
Tokenizer::openFile: Unable to open file /home/salleykurt/.slade3/mapwindow.layout
Setting up the OpenGL context
Failed to setup the OpenGL context
Opening map e1m1
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
```

### Screenshots

![DESCRIPTION](LINK.png)

**Comment by Blzut3** [comment] 2024-08-11 01:19
Is this a Chromebook?

**Comment by pickleman64** [comment] 2024-08-11 05:19
Yes im on a cromebook

**Comment by Blzut3** [comment] 2024-08-11 05:22
We've gotten a couple of reports like this.  Can you give the model of your Chromebook?

Ultimately at this time Slade seems to be incompatible with ChromeOS.  I am curious what hardware is being used since I have no idea why this would be the case though.

**Comment by Blzut3** [comment] 2024-08-18 23:35
Duplicate of #1658

**Closed by Blzut3** 2024-08-18 23:35 UTC
Labels: crash bug
