### ISSUE TITLE
Viewing a bigfont crashes SLADE 3 (DevBuilds)

### ISSUE THREAD

**Issue by SanyaWaffles** [sirjuddington/SLADE#889] opened 2018-06-23 15:03 UTC
**SLADE Version**: (Latest devbuilds)
**Operating System**: Windows 10
**Issue Details**:
Whenever I load a mod that has a BIGFONT format lump/file inside it, nothing happens until I click on the entry in question. This causes Slade 3 to hang, and then crash ungracefully.

**Comment by Gaerzi** [comment] 2018-06-23 16:17
Works for me with dbigfont.lmp from gzdoom.pk3.

As always with issues caused by specific lumps, providing the actual lump that causes the problem helps.

**Comment by SanyaWaffles** [comment] 2018-06-24 16:48
[ORIGFONT.zip](https://github.com/sirjuddington/SLADE/files/2130989/ORIGFONT.zip)


the resource I got it from was DoomDelta_v2. Any time I click on this to view it, it would crash SLADE3.

**Comment by Gaerzi** [comment] 2018-06-24 20:16
Still works for me, including directly from Doom Delta. Strange.

**Comment by SanyaWaffles** [comment] 2018-06-25 17:14
What version are you using?

**Comment by Gaerzi** [comment] 2018-06-25 18:38
3.1.2 Beta 5, XP-compatible build.

**Comment by SanyaWaffles** [comment] 2018-06-26 17:22
I'll test the XP compatible build you are using. Mine right now is the latest Git devbuild.

**Comment by SanyaWaffles** [comment] 2018-07-05 22:12
This problem still exists in recent Git Builds.

**Comment by MajorCooke** [comment] 2018-12-19 18:03
Same here. This issue still persists.

**Comment by Candlemass** [comment] 2019-02-11 02:43
I'm experiencing the same problem. Came here to report this and found there was already an open issue.

Build 3.1.4

**Comment by Xymph** [comment] 2019-02-12 13:27
Same here on v3.1.4 with lump DBIGFONT in the new [Eviternity.wad](https://www.doomworld.com/idgames/?id=19304). It doesn't _always_ crash the first time I select the lump entry, but inevitably always does when traversing up and down the directory around that lump.

**Comment by sirjuddington** [comment] 2019-11-07 07:15
This should have been fixed with #1055 
Feel free to reopen if it isn't

**Closed by sirjuddington** 2019-11-07 07:15 UTC
Labels: crash bug
