### ISSUE TITLE
building textured bridges using sectors

### ISSUE THREAD

**Issue by D3X1KAXYZ** [sirjuddington/SLADE#540] opened 2016-06-08 05:47 UTC
Feature Request

- texture properties for bridges

- set bridge dimensions using a sector

_side note: if possible please add an auto save feature. Slade likes to crash on me and i lose my progress. as of right now it does not bother me as i am just experimenting, but i hope to start making mods in the near future._
_also 3.1.1.2 is much more stable than 3.1.1.1 for me. it still crashes but not as frequently as 3.1.1.1 did.._

**Comment by Gaerzi** [comment] 2016-06-08 20:11
I believe this to be a duplicate of #205.

**Closed by Gaerzi** 2016-06-08 20:11 UTC

**Comment by D3X1KAXYZ** [comment] 2016-06-10 14:48
# @Gaerzi lol yes it is. very sorry about that.
