### ISSUE TITLE
Crashes when saving zip files

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#444] opened 2016-01-31 18:44 UTC
Mentioned [here](http://forum.zdoom.org/viewtopic.php?f=3&t=24955&view=unread#p881209). Since the ZipArchive::write() has its own way of writing directly to file (most other archive types write to mem chunk and then export the mem chunk), it might be worth to review that part of the code for what could cause a crash during a save.

**Comment by sirjuddington** [comment] 2016-02-07 22:22
Hmm, I can't see anywhere it might do that, unless something in `entries` or `c_entries` is null somehow. Hard to tell without a stack trace or something like that. He says it corrupts the zip file so I'm assuming it's happening during the actual save entry loop and not before or after it

**Comment by sirjuddington** [comment] 2016-04-13 23:55
Going to close this one since it is possibly fixed (and I could never reproduce it)

**Closed by sirjuddington** 2016-04-13 23:55 UTC
Labels: crash bug, resource editor
