### ISSUE TITLE
Crash exiting SLADE after opening a certain WAD

### ISSUE THREAD

**Issue by JPLeBreton** [sirjuddington/SLADE#873] opened 2018-05-12 19:30 UTC
**SLADE Version**: latest master
**Operating System**: Linux

**Issue Details**:
Steps to repro:
1. open [this WAD](https://www.dropbox.com/s/i51kwc591mouyq5/doomcenter.zip?dl=0) in SLADE
2. once SLADE loads, close it
3. observe: SLADE crashes on exit with this text:
```
corrupted size vs. prev_size
Aborted (core dumped)
```
When it does this it doesn't appear to leave behind a log with any more detailed info, or save any settings from the session.

**Comment by JPLeBreton** [comment] 2018-05-13 20:11
Edit: updated with repro steps.

Oddly, a log did show up recently, though I can't guarantee it's exactly the repro steps described above.

```
Version: 3.1.2 Beta 5
Current action: arch_mapeditor
Operating System: Linux 4.16.8-1-ARCH x86_64
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 396.24

Stack Trace:
0: [unknown location] [unknown:-1401620676]
1: [unknown location] [unknown:-1487697280]
2: [unknown location] wxString::ToAscii(char) const
3: [unknown location] Property::getIntValue(bool) const
4: [unknown location] MOPGIntWithArgsProperty::updateArgs(wxPGProperty**)
5: [unknown location] MapObjectPropsPanel::updateArgs(MOPGIntWithArgsProperty*)
6: [unknown location] non-virtual thunk to MOPGIntWithArgsProperty::OnSetValue()
7: [unknown location] wxPGProperty::SetValue(wxVariant, wxVariant*, int)
8: [unknown location] MOPGIntProperty::openObjects(std::vector<MapObject*, std::allocator<MapObject*> >&)
9: [unknown location] MapObjectPropsPanel::openObjects(std::vector<MapObject*, std::allocator<MapObject*> >&)
10: [unknown location] MapEditContext::selectionUpdated()
11: [unknown location] MapEditContext::clearMap()
12: [unknown location] MapEditorWindow::openMap(Archive::MapDesc)
13: [unknown location] MapEditorWindow::chooseMap(Archive*)
14: [unknown location] ArchivePanel::handleAction(wxString)
15: [unknown location] SActionHandler::doAction(wxString)
16: [unknown location] SLADEWxApp::onMenu(wxCommandEvent&)
17: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
18: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
19: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
20: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
21: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
22: [unknown location] wxWindowBase::TryAfter(wxEvent&)
23: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
24: [unknown location] wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*)
25: [unknown location] wxMenuBase::SendEvent(int, int)
26: [unknown location] [unknown:-1391037573]
27: [unknown location] g_closure_invoke
28: [unknown location] [unknown:-1464603072]
29: [unknown location] g_signal_emit_valist
30: [unknown location] g_signal_emit
31: [unknown location] gtk_widget_activate
32: [unknown location] gtk_menu_shell_activate_item
33: [unknown location] [unknown:-1439850176]
34: [unknown location] [unknown:-1439926324]
35: [unknown location] g_closure_invoke
36: [unknown location] [unknown:-1464603702]
37: [unknown location] g_signal_emit_valist
38: [unknown location] g_signal_emit
39: [unknown location] [unknown:-1438768587]
40: [unknown location] gtk_propagate_event
41: [unknown location] gtk_main_do_event
42: [unknown location] [unknown:-1443631778]
43: [unknown location] g_main_context_dispatch
44: [unknown location] [unknown:-1467673167]
45: [unknown location] g_main_loop_run
46: [unknown location] gtk_main
47: [unknown location] wxGUIEventLoop::DoRun()
48: [unknown location] wxEventLoopBase::Run()
49: [unknown location] wxAppConsoleBase::MainLoop()
50: [unknown location] wxEntry(int&, wchar_t**)
51: [unknown location] main
52: [unknown location] __libc_start_main
53: [unknown location] _start

Last Log Messages:
execute "/home/jpl/game/zdbsp/build/zdbsp  --gl --comments  "/tmp/SLADE3/sladetemp.wad" --output="/tmp/SLADE3/sladetemp.wad""
Nodebuilder output:
----MAP01----
   0.281 seconds.

Total time: 0.282 seconds.
Opening archive /home/jpl/game/doom/pwad/doomcenter/DooM Center.wad
MAPINFO not implemented
Opening took 247 ms
Read game configuration "doom2" + "zdoom"
```

**Comment by crisisinaptica** [comment] 2018-11-10 21:33
I can't reproduce this in current master.

**Comment by sirjuddington** [comment] 2019-11-07 13:20
I could never reproduce this one either, going to close the issue, feel free to reopen if it still happens

**Closed by sirjuddington** 2019-11-07 13:20 UTC
Labels: crash bug
