### ISSUE TITLE
Sudden crash after right clicking a sector in map editor and selecting sector properties.

### ISSUE THREAD

**Issue by Laerrus811** [sirjuddington/SLADE#1533] opened 2023-06-19 17:09 UTC
**SLADE Version**: (3.X.X.x)
**Operating System**: (Windows/Linux/OSX)

**Issue Details**:
Was editing in 2d map mode, right clicked on a sector and selected sector properties when the crash happened.

Updated UPDATE:
It happens even when nothing is done in sector properties, I right click, select properties of any sector, do nothing, click okay, and it crashes.

UPDATE:
It happened again; new file generated is included below; it happens after I assign a new sector tag and hit okay, then it crashes.

Version: 3.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 7 (build 7601, Service Pack 1), 64-bit edition
Graphics Vendor: ATI Technologies Inc.
Graphics Hardware: AMD Radeon(TM) R5 240
OpenGL Version: 4.5.13456 Compatibility Profile Context 21.19.144.32768

Stack Trace:
0: [unknown location] [unknown:1064276169]
1: [unknown location] [unknown:1064479576]
2: [unknown location] [unknown:1063993298]
3: [unknown location] [unknown:1063820973]
4: [unknown location] [unknown:1063966665]
5: [unknown location] [unknown:1059265108]
6: [unknown location] [unknown:1058567926]
7: [unknown location] [unknown:1068231860]
8: [unknown location] [unknown:1068397231]
9: [unknown location] [unknown:1068400131]
10: [unknown location] [unknown:1068400993]
11: [unknown location] [unknown:1068397018]
12: [unknown location] [unknown:1068400926]
13: [unknown location] [unknown:1069425827]
14: [unknown location] [unknown:1068397100]
15: [unknown location] [unknown:1068399978]
16: [unknown location] [unknown:1069923557]
17: [unknown location] [unknown:1070221913]
18: [unknown location] [unknown:1069452566]
19: [unknown location] [unknown:1070676655]
20: [unknown location] [unknown:1070678544]
21: [unknown location] [unknown:1069520597]
22: [unknown location] TranslateMessageEx
23: [unknown location] TranslateMessage
24: [unknown location] [unknown:1069442113]
25: [unknown location] [unknown:1069414310]
26: [unknown location] [unknown:1063996190]
27: [unknown location] [unknown:1063862832]
28: [unknown location] [unknown:1064321018]
29: [unknown location] [unknown:1068231860]
30: [unknown location] [unknown:1068397231]
31: [unknown location] [unknown:1068400131]
32: [unknown location] [unknown:1068400993]
33: [unknown location] [unknown:1068397018]
34: [unknown location] [unknown:1068399978]
35: [unknown location] [unknown:1069458339]
36: [unknown location] [unknown:1069484787]
37: [unknown location] [unknown:1069495432]
38: [unknown location] [unknown:1069520597]
39: [unknown location] TranslateMessageEx
40: [unknown location] CallWindowProcW
41: [unknown location] CallWindowProcW
42: [unknown location] glDebugEntry
43: [unknown location] TranslateMessageEx
44: [unknown location] CallWindowProcW
45: [unknown location] CallWindowProcW
46: [unknown location] [unknown:1067835937]
47: [unknown location] TranslateMessageEx
48: [unknown location] TranslateMessage
49: [unknown location] [unknown:1070826668]
50: [unknown location] [unknown:1068884483]
51: [unknown location] [unknown:1068885018]
52: [unknown location] [unknown:1068237335]
53: [unknown location] [unknown:1068922812]
54: [unknown location] [unknown:1068385928]
55: [unknown location] [unknown:1073217246]
56: [unknown location] BaseThreadInitThunk
57: [unknown location] RtlUserThreadStart

Last Log Messages:
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map map01B
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by Laerrus811** [comment] 2023-06-19 17:10
For some reason it removed the report when I posted, here is what Slade reported.

Version: 3.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 7 (build 7601, Service Pack 1), 64-bit edition
Graphics Vendor: ATI Technologies Inc.
Graphics Hardware: AMD Radeon(TM) R5 240
OpenGL Version: 4.5.13456 Compatibility Profile Context 21.19.144.32768

Stack Trace:
0: [unknown location] [unknown:1071878345]
1: [unknown location] [unknown:1072081752]
2: [unknown location] [unknown:1071595474]
3: [unknown location] [unknown:1071423149]
4: [unknown location] [unknown:1071568841]
5: [unknown location] [unknown:1066867284]
6: [unknown location] [unknown:1066170102]
7: [unknown location] [unknown:1075834036]
8: [unknown location] [unknown:1075999407]
9: [unknown location] [unknown:1076002307]
10: [unknown location] [unknown:1076003169]
11: [unknown location] [unknown:1075999194]
12: [unknown location] [unknown:1076003102]
13: [unknown location] [unknown:1077028003]
14: [unknown location] [unknown:1075999276]
15: [unknown location] [unknown:1076002154]
16: [unknown location] [unknown:1077525733]
17: [unknown location] [unknown:1077824089]
18: [unknown location] [unknown:1077054742]
19: [unknown location] [unknown:1078278831]
20: [unknown location] [unknown:1078280720]
21: [unknown location] [unknown:1077122773]
22: [unknown location] TranslateMessageEx
23: [unknown location] TranslateMessage
24: [unknown location] [unknown:1077044289]
25: [unknown location] [unknown:1077016486]
26: [unknown location] [unknown:1071598366]
27: [unknown location] [unknown:1071465008]
28: [unknown location] [unknown:1071923194]
29: [unknown location] [unknown:1075834036]
30: [unknown location] [unknown:1075999407]
31: [unknown location] [unknown:1076002307]
32: [unknown location] [unknown:1076003169]
33: [unknown location] [unknown:1075999194]
34: [unknown location] [unknown:1076002154]
35: [unknown location] [unknown:1077060515]
36: [unknown location] [unknown:1077086963]
37: [unknown location] [unknown:1077097608]
38: [unknown location] [unknown:1077122773]
39: [unknown location] TranslateMessageEx
40: [unknown location] CallWindowProcW
41: [unknown location] CallWindowProcW
42: [unknown location] glDebugEntry
43: [unknown location] TranslateMessageEx
44: [unknown location] CallWindowProcW
45: [unknown location] CallWindowProcW
46: [unknown location] [unknown:1075438113]
47: [unknown location] TranslateMessageEx
48: [unknown location] TranslateMessage
49: [unknown location] [unknown:1078428844]
50: [unknown location] [unknown:1076486659]
51: [unknown location] [unknown:1076487194]
52: [unknown location] [unknown:1075839511]
53: [unknown location] [unknown:1076524988]
54: [unknown location] [unknown:1075988104]
55: [unknown location] [unknown:1080819422]
56: [unknown location] BaseThreadInitThunk
57: [unknown location] RtlUserThreadStart

Last Log Messages:
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Opening map map01B
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors
Warning: Action "mapw_item_properties" not handled

**Comment by sirjuddington** [comment] 2023-06-21 07:33
Duplicate of #1512 (fixed for next release)

**Closed by sirjuddington** 2023-06-21 07:33 UTC
