### ISSUE TITLE
Truecolor mode in TEXTURES editor not applying to first patch

### ISSUE THREAD

**Issue by azamorapl** [sirjuddington/SLADE#1266] opened 2021-06-14 23:01 UTC
**SLADE Version**: 3.2.0.b3 and 3.1.13
**Operating System**: Windows

**Issue Details**:
When selecting the "Truecolor mode" in the TEXTURES editor, the first patch in the texture is not displayed in truecolor. This also affects the image that gets exported when the "Export as PNG" option is selected.

I tested duplicating the first patch and it was displayed correctly, so it seems like this only affects the first patch in the texture.

Example:

<img src="https://imgur.com/hpPkwgu.jpg" />

**Comment by sirjuddington** [comment] 2021-06-18 00:42
Hmm I can't reproduce this one, and can't see how it would happen just looking at the code for it. If possible would you be able to put together a minimal example wad/pk3 that shows the issue?

**Comment by azamorapl** [comment] 2021-06-18 01:40
While making the isolated example I understand what happened.

The TEXTURES lump of the wad I'm editing has a self-referencing texture, and another texture that references said texture. That is the one that is not getting rendered correctly. See the attached example:

[truecolortest.zip](https://github.com/sirjuddington/SLADE/files/6674047/truecolortest.zip)

**Comment by sirjuddington** [comment] 2021-06-22 14:30
Should be fixed in next beta

**Closed by sirjuddington** 2021-06-22 14:30 UTC
Labels: bug, texture editor
