### ISSUE TITLE
Crashing in map editor

### ISSUE THREAD

**Issue by MegaKonami** [sirjuddington/SLADE#1519] opened 2023-06-05 23:01 UTC
**SLADE Version**: 3.2.3 (Latest)
**Operating System**: Windows
**Issue Details**:
From what I'm picking up, the map editor crashes when applying edits made to sector properties.

Stack Trace:
```
Version: 3.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 11 (build 22621), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 526.98

Stack Trace:
0: [unknown location] [unknown:409768137]
1: [unknown location] [unknown:409971544]
2: [unknown location] [unknown:409485266]
3: [unknown location] [unknown:409312941]
4: [unknown location] [unknown:409458633]
5: [unknown location] [unknown:404757076]
6: [unknown location] [unknown:404059894]
7: [unknown location] [unknown:413723828]
8: [unknown location] [unknown:413889199]
9: [unknown location] [unknown:413892099]
10: [unknown location] [unknown:413892961]
11: [unknown location] [unknown:413888986]
12: [unknown location] [unknown:413892894]
13: [unknown location] [unknown:414917795]
14: [unknown location] [unknown:413889068]
15: [unknown location] [unknown:413891946]
16: [unknown location] [unknown:415415525]
17: [unknown location] [unknown:415713881]
18: [unknown location] [unknown:414944534]
19: [unknown location] [unknown:416168623]
20: [unknown location] [unknown:416170512]
21: [unknown location] [unknown:415012565]
22: [unknown location] DispatchMessageW
23: [unknown location] DispatchMessageW
24: [unknown location] [unknown:414934081]
25: [unknown location] [unknown:414906278]
26: [unknown location] [unknown:409488158]
27: [unknown location] [unknown:409354800]
28: [unknown location] [unknown:409812986]
29: [unknown location] [unknown:413723828]
30: [unknown location] [unknown:413889199]
31: [unknown location] [unknown:413892099]
32: [unknown location] [unknown:413892961]
33: [unknown location] [unknown:413888986]
34: [unknown location] [unknown:413891946]
35: [unknown location] [unknown:414950307]
36: [unknown location] [unknown:414976755]
37: [unknown location] [unknown:414987400]
38: [unknown location] [unknown:415012565]
39: [unknown location] DispatchMessageW
40: [unknown location] CallWindowProcW
41: [unknown location] wglSwapBuffers
42: [unknown location] DispatchMessageW
43: [unknown location] CallWindowProcW
44: [unknown location] [unknown:413327905]
45: [unknown location] DispatchMessageW
46: [unknown location] DispatchMessageW
47: [unknown location] [unknown:416318636]
48: [unknown location] [unknown:414376451]
49: [unknown location] [unknown:414376986]
50: [unknown location] [unknown:413729303]
51: [unknown location] [unknown:414414780]
52: [unknown location] [unknown:413877896]
53: [unknown location] [unknown:418709214]
54: [unknown location] BaseThreadInitThunk
55: [unknown location] RtlUserThreadStart

Last Log Messages:
Warning: Action "mapw_item_properties" not handled
Warning: Action "mapw_item_properties" not handled
execute "D:/Programs/zdbsp-1.19/zdbsp.exe  "C:\Users\username\AppData\Roaming\SLADE3\temp\sladetemp.wad" --output="C:\Users\username\AppData\Roaming\SLADE3\temp\sladetemp.wad""
Nodebuilder output:
----MAP01----
   0.001 seconds.

Total time: 0.002 seconds.
Creating backup D:/Programs/gzdoom-4-10-0-Windows-64bit/ULTIMATEDM.WAD.bak
Warning: Action "mapw_item_properties" not handled
```

**Comment by Meepster-836** [comment] 2023-06-08 22:57
A similar bug occurs for me when doing the same thing, on Linux Mint 21.3 (or whatever the latest version is), RX 6700 XT.

**Comment by sirjuddington** [comment] 2023-06-09 10:43
Closing as duplicate of #1512 (is fixed for the next version)

**Closed by sirjuddington** 2023-06-09 10:43 UTC
