### ISSUE TITLE
Ability to rearrange the order of folders in PK3?

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1006] opened 2018-12-31 17:23 UTC
**SLADE Version**: (3.1.4)
**Operating System**: (Windows)

**Issue Details**:
SLADE currently allows you to rearrange the order of files within a PK3, but not the order of folders.  Requesting the ability to rearrange the order of folders within a PK3 if possible.

**Comment by sirjuddington** [comment] 2022-03-28 12:04
Duplicate of #313

**Closed by sirjuddington** 2022-03-28 12:04 UTC
Labels: resource editor, feature request
