### ISSUE TITLE
Cut-undo a big folder crashes SLADE Beta 5

### ISSUE THREAD

**Issue by Xane123** [sirjuddington/SLADE#827] opened 2017-12-17 16:32 UTC
**SLADE Version**: 3.1.2 Beta 5
**Operating System**: Windows

**Issue Details**:
It doesn't happen with single files, but if a folder with hundreds of files inside is cut (CTRL+X) then undo (CTRL-Z), a crash is guaranteed to happen. In Beta 4, no error would appear, but in Beta 5 the dialog appears.

Use [this PK3 file from my game](https://drive.google.com/open?id=120FFLujelpp-Xo2ktLG_jIEWUpTfJvID) to see this for yourself.

**Crash Info**:
> Version: 3.1.2 Beta 5
Current action: main_undo
Operating System: Windows 10 (build 16299), 64-bit edition
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

> Stack Trace:
0: (c:\dev\slade-build\src\archive\archiveentry.cpp:176) ArchiveEntry::getParent
1: (c:\dev\slade-build\src\general\resourcemanager.cpp:148) EntryResource::getEntry
2: (c:\dev\slade-build\src\general\resourcemanager.cpp:464) ResourceManager::getAllPatchEntries
3: (c:\dev\slade-build\src\mapeditor\maptexturemanager.cpp:551) MapTextureManager::buildTexInfoList
4: (c:\dev\slade-build\src\mapeditor\maptexturemanager.cpp:627) MapTextureManager::onAnnouncement
5: (c:\dev\slade-build\src\general\listenerannouncer.cpp:148) Announcer::announce
6: (c:\dev\slade-build\src\general\listenerannouncer.cpp:161) Announcer::announce
7: (c:\dev\slade-build\src\general\resourcemanager.cpp:650) ResourceManager::onAnnouncement
8: (c:\dev\slade-build\src\general\listenerannouncer.cpp:148) Announcer::announce
9: (c:\dev\slade-build\src\archive\archive.cpp:721) Archive::entryStateChanged
10: (c:\dev\slade-build\src\archive\archiveentry.cpp:285) ArchiveEntry::setState
11: (c:\dev\slade-build\src\archive\archivetreenode.cpp:528) ArchiveTreeNode::merge
12: (c:\dev\slade-build\src\archive\archivetreenode.cpp:537) ArchiveTreeNode::merge
13: (c:\dev\slade-build\src\archive\archive.cpp:294) DirCreateDeleteUS::doUndo
14: (c:\dev\slade-build\src\general\undoredo.cpp:86) UndoLevel::doUndo
15: (c:\dev\slade-build\src\general\undoredo.cpp:269) UndoManager::undo
16: (c:\dev\slade-build\src\maineditor\ui\archivepanel.cpp:556) ArchivePanel::undo
17: (c:\dev\slade-build\src\maineditor\ui\archivemanagerpanel.cpp:1274) ArchiveManagerPanel::undo
18: (c:\dev\slade-build\src\maineditor\ui\mainwindow.cpp:559) MainWindow::handleAction
19: (c:\dev\slade-build\src\general\saction.cpp:529) SActionHandler::doAction
20: (c:\dev\slade-build\src\application\sladewxapp.cpp:698) SLADEWxApp::onMenu
21: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:658) wxAppConsoleBase::HandleEvent
22: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:669) wxAppConsoleBase::CallEventHandler
23: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1383) wxEvtHandler::ProcessEventIfMatchesId
24: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1831) wxEvtHandler::SearchDynamicEventTable
25: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1574) wxEvtHandler::TryHereOnly
26: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1484) wxEvtHandler::ProcessEvent
27: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1448) wxEvtHandler::TryAfter
28: (f:\programming\libs\wxwidgets-3.1.0\src\common\wincmn.cpp:3463) wxWindowBase::TryAfter
29: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1497) wxEvtHandler::ProcessEvent
30: (f:\programming\libs\wxwidgets-3.1.0\src\common\wincmn.cpp:3457) wxWindowBase::TryAfter
31: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1497) wxEvtHandler::ProcessEvent
32: (f:\programming\libs\wxwidgets-3.1.0\src\common\event.cpp:1669) wxEvtHandler::SafelyProcessEvent
33: (f:\programming\libs\wxwidgets-3.1.0\src\common\menucmn.cpp:673) wxMenuBase::DoProcessEvent
34: (f:\programming\libs\wxwidgets-3.1.0\src\common\menucmn.cpp:643) wxMenuBase::SendEvent
35: (f:\programming\libs\wxwidgets-3.1.0\src\common\framecmn.cpp:294) wxFrameBase::ProcessCommand
36: (f:\programming\libs\wxwidgets-3.1.0\src\msw\frame.cpp:799) wxFrame::HandleCommand
37: (f:\programming\libs\wxwidgets-3.1.0\src\msw\frame.cpp:856) wxFrame::MSWWindowProc
38: (f:\programming\libs\wxwidgets-3.1.0\src\msw\window.cpp:2668) wxWndProc
39: [unknown location] AddClipboardFormatListener
40: [unknown location] EndTask
41: [unknown location] EndTask
42: [unknown location] CallNextHookEx
43: [unknown location] IsWindow
44: [unknown location] KiUserCallbackDispatcher
45: (f:\programming\libs\wxwidgets-3.1.0\src\msw\accel.cpp:150) wxAcceleratorTable::Translate
46: (f:\programming\libs\wxwidgets-3.1.0\src\msw\frame.cpp:734) wxFrame::MSWDoTranslateMessage
47: (f:\programming\libs\wxwidgets-3.1.0\include\wx\msw\frame.h:98) wxFrame::MSWTranslateMessage
48: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:134) wxGUIEventLoop::PreProcessMessage
49: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:163) wxGUIEventLoop::ProcessMessage
50: (f:\programming\libs\wxwidgets-3.1.0\src\msw\evtloop.cpp:229) wxGUIEventLoop::Dispatch
51: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:233) wxEventLoopManual::ProcessEvents
52: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:273) wxEventLoopManual::DoRun
53: (f:\programming\libs\wxwidgets-3.1.0\src\common\evtloopcmn.cpp:76) wxEventLoopBase::Run
54: (f:\programming\libs\wxwidgets-3.1.0\src\common\appbase.cpp:380) wxAppConsoleBase::MainLoop
55: (f:\programming\libs\wxwidgets-3.1.0\src\common\init.cpp:503) wxEntryReal
56: (f:\programming\libs\wxwidgets-3.1.0\src\msw\main.cpp:181) wxEntry
57: (f:\programming\libs\wxwidgets-3.1.0\src\msw\main.cpp:289) wxEntry
58: (c:\dev\slade-build\src\application\sladewxapp.cpp:476) WinMain
59: (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253) __scrt_common_main_seh
60: [unknown location] BaseThreadInitThunk
61: [unknown location] RtlGetAppContainerNamedObjectPath
62: [unknown location] RtlGetAppContainerNamedObjectPath

> Last Log Messages:
Read game configuration "doom2" + "zdoom"
SLADE Initialisation OK
Checking for updates...
Latest stable release: v3115 "3.1.1.5"
Latest beta release: v3120_b5 "3.1.2 Beta 5"
Already up-to-date
Opening archive C:\Users\Myers\Programs\Mary's Magical Adventure (Reshade)\aaaaaa\test.pk3
Opening took 1740 ms
Opening archive C:/Users/Myers/Programs/Mary's Magical Adventure (Reshade)/aaaaaa/test.pk3
Opening took 1588 ms

**Comment by sirjuddington** [comment] 2018-02-12 04:37
Can't reproduce this one, however it may be fixed with the changes in https://github.com/sirjuddington/SLADE/commit/ed0c6e9c3dd3b453bdce7f5e6136eee6534e63ff

Going to close it for now, feel free to reopen the issue if it still happens in beta 6

**Closed by sirjuddington** 2018-02-12 04:37 UTC
Labels: crash bug, resource editor
