### ISSUE TITLE
crash when trying to save music wad

### ISSUE THREAD

**Issue by L3gend** [sirjuddington/SLADE#473] opened 2016-03-06 04:17 UTC
**SLADE Version**: (3.1 1 0)
**Operating System**: (Windows xp)

**Issue Details**:
I am trying to make a usable music wad with the psx 20th anniversary soundtrack.  But whenever I try to save the wad, slade crashes. It gets an unhandled exception. I am specifically trying to put it into a wad file rather than pk3 so it can be used with doom retro. Also am trying to use the music in ogg format.

Here is the stack file:
`Version: 3.1.1
Current action: aman_save
Operating System: Windows XP (build 2600, Service Pack 3)
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] [unknown:0]
1: (c:\dev\slade3\src\maineditor\mainwindow.cpp:437) MainWindow::createStartPage
2: (c:\dev\slade3\src\maineditor\mainwindow.cpp:1108) MainWindow::onActivate
3: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
4: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
5: (f:\programming\libs\wxwidgets\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
6: (f:\programming\libs\wxwidgets\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
7: (f:\programming\libs\wxwidgets\src\common\event.cpp:1491) wxEvtHandler::ProcessEvent
8: (f:\programming\libs\wxwidgets\src\common\event.cpp:1554) wxEvtHandler::DoTryChain
9: (f:\programming\libs\wxwidgets\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
10: (f:\programming\libs\wxwidgets\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
11: (f:\programming\libs\wxwidgets\src\msw\window.cpp:4069) wxWindow::HandleActivate
12: (f:\programming\libs\wxwidgets\src\msw\window.cpp:2833) wxWindow::MSWHandleMessage
13: (f:\programming\libs\wxwidgets\src\msw\window.cpp:3645) wxWindow::MSWWindowProc
14: (f:\programming\libs\wxwidgets\src\msw\toplevel.cpp:467) wxTopLevelWindowMSW::MSWWindowProc
15: (f:\programming\libs\wxwidgets\src\msw\frame.cpp:890) wxFrame::MSWWindowProc
16: (f:\programming\libs\wxwidgets\src\msw\window.cpp:2711) wxWndProc
17: [unknown location] GetDC
18: [unknown location] GetDC
19: [unknown location] DefWindowProcW
20: [unknown location] DefWindowProcW
21: [unknown location] KiUserCallbackDispatcher
22: [unknown location] GetCursorFrameInfo
23: [unknown location] SoftModalMessageBox
24: [unknown location] MessageBoxIndirectA
25: [unknown location] MessageBoxTimeoutW
26: [unknown location] MessageBoxExW
27: [unknown location] MessageBoxW
28: (f:\programming\libs\wxwidgets\src\common\msgout.cpp:133) wxMessageOutputBest::Output
29: (f:\programming\libs\wxwidgets\src\common\msgout.cpp:86) wxMessageOutput::DoPrintfWchar
30: (f:\programming\libs\wxwidgets\include\wx\msgout.h:39) wxMessageOutputBase::Printf<wxString>
31: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:650) wxAppConsoleBase::OnUnhandledException
32: (f:\programming\libs\wxwidgets\src\common\init.cpp:497) wxEntryReal
33: (f:\programming\libs\wxwidgets\src\msw\main.cpp:188) wxEntry
34: (f:\programming\libs\wxwidgets\src\msw\main.cpp:415) wxEntry
35: (c:\dev\slade3\src\application\mainapp.cpp:421) WinMain
36: (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264) __scrt_common_main_seh
37: [unknown location] RegisterWaitForInputIdle

Last Log Messages:
`

**Comment by Gaerzi** [comment] 2016-03-06 10:55
The stack trace befuddles me. Why does it crash in createStartPage when what you're doing is saving a file? I'd expect the crash to be somewhere in WadArchive:: code, but here what it says is that the main window is activated while the active page is the start page (rather than your archive).

**Comment by sirjuddington** [comment] 2016-03-06 13:23
Did you use the 'Copy Stack Trace' button? There should be at least something in the 'Last Log Messages' bit. The log messages might help to see if something else is wrong.

**Comment by L3gend** [comment] 2016-03-06 18:21
I recreated the crash to double check the stack message. There is nothing under the 'last log messages'. 

When I try to save, it gives me the error for the unhandled exception then asks me if I want to abort, retry, or ignore. I can only get the stack trace if I click abort. But, after I click abort, the dialogue pops up a second time and I have to click abort again for a second time. Then it closes and gives me the report. 

I also tried both off and mp3 format with the same results. 

I am adding the music files by taking an existing music wad, and importing the new files in their place to try and avoid having to rename all files. 

I don't know if any of this is helpful.  Also, I was getting this same error with the previous version of slade as well.

**Comment by L3gend** [comment] 2016-03-06 18:24
Here is another stack file just in case. Looks like it differs slightly from the one I first posted. 

`Version: 3.1.1
Current action: aman_save
Operating System: Windows XP (build 2600, Service Pack 3)
Graphics Vendor: Intel
Graphics Hardware: Intel 945GM
OpenGL Version: 1.4.0 - Build 7.14.10.4814

Stack Trace:
0: (c:\dev\slade3\src\maineditor\mainwindow.cpp:436) MainWindow::createStartPage
1: (c:\dev\slade3\src\maineditor\mainwindow.cpp:1108) MainWindow::onActivate
2: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:612) wxAppConsoleBase::HandleEvent
3: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:623) wxAppConsoleBase::CallEventHandler
4: (f:\programming\libs\wxwidgets\src\common\event.cpp:1751) wxEvtHandler::SearchDynamicEventTable
5: (f:\programming\libs\wxwidgets\src\common\event.cpp:1585) wxEvtHandler::TryHereOnly
6: (f:\programming\libs\wxwidgets\src\common\event.cpp:1491) wxEvtHandler::ProcessEvent
7: (f:\programming\libs\wxwidgets\src\common\event.cpp:1554) wxEvtHandler::DoTryChain
8: (f:\programming\libs\wxwidgets\src\common\event.cpp:1495) wxEvtHandler::ProcessEvent
9: (f:\programming\libs\wxwidgets\src\common\event.cpp:1647) wxEvtHandler::SafelyProcessEvent
10: (f:\programming\libs\wxwidgets\src\msw\window.cpp:4069) wxWindow::HandleActivate
11: (f:\programming\libs\wxwidgets\src\msw\window.cpp:2833) wxWindow::MSWHandleMessage
12: (f:\programming\libs\wxwidgets\src\msw\window.cpp:3645) wxWindow::MSWWindowProc
13: (f:\programming\libs\wxwidgets\src\msw\toplevel.cpp:467) wxTopLevelWindowMSW::MSWWindowProc
14: (f:\programming\libs\wxwidgets\src\msw\frame.cpp:890) wxFrame::MSWWindowProc
15: (f:\programming\libs\wxwidgets\src\msw\window.cpp:2711) wxWndProc
16: [unknown location] GetDC
17: [unknown location] GetDC
18: [unknown location] DefWindowProcW
19: [unknown location] DefWindowProcW
20: [unknown location] KiUserCallbackDispatcher
21: [unknown location] GetCursorFrameInfo
22: [unknown location] SoftModalMessageBox
23: [unknown location] MessageBoxIndirectA
24: [unknown location] MessageBoxTimeoutW
25: [unknown location] MessageBoxExW
26: [unknown location] MessageBoxW
27: (f:\programming\libs\wxwidgets\src\common\msgout.cpp:133) wxMessageOutputBest::Output
28: (f:\programming\libs\wxwidgets\src\common\msgout.cpp:86) wxMessageOutput::DoPrintfWchar
29: (f:\programming\libs\wxwidgets\include\wx\msgout.h:39) wxMessageOutputBase::Printf<wxString>
30: (f:\programming\libs\wxwidgets\src\common\appbase.cpp:650) wxAppConsoleBase::OnUnhandledException
31: (f:\programming\libs\wxwidgets\src\common\init.cpp:497) wxEntryReal
32: (f:\programming\libs\wxwidgets\src\msw\main.cpp:188) wxEntry
33: (f:\programming\libs\wxwidgets\src\msw\main.cpp:415) wxEntry
34: (c:\dev\slade3\src\application\mainapp.cpp:421) WinMain
35: (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264) __scrt_common_main_seh
36: [unknown location] RegisterWaitForInputIdle

Last Log Messages:
`

**Comment by sirjuddington** [comment] 2016-03-06 22:46
I doubt it has anything to do with the format of the music. Can you save other archives fine? It may be something to do with the size of the archive. Also, open the console before saving (`Ctrl+2`) and see if there are any error-looking messages in there.

**Comment by Gaerzi** [comment] 2016-03-06 23:27
Again, the stack trace pretends the issue is in the start page, which makes no sense to me. Do you even have it open when you save?

**Comment by L3gend** [comment] 2016-03-07 01:57
Not sure what you mean by 'do you even have it open when you save?' Do I have what open exactly? Slade? Yes. The wad archive itself? yes.

I have had no problems in the past saving wads before. 

Here is what is displayed in the console after I open slade and load the wad I am trying to save:

`17:45:11: SLADE - It's a Doom Editor
17:45:11: Version 3.1.1
17:45:11: Written by Simon Judd, 2008-2016
17:45:11: Compiled with wxWidgets 3.0.2 and SFML 2.3
17:45:11: --------------------------------
17:45:11: Windows Version: 5.1
17:45:11: Loading configuration
17:45:11: Loading resources
17:45:11: Loading icons
17:45:11: Loading entry types
17:45:11: Loading text languages
17:45:12: Loading text style sets
17:45:12: Loading colour configuration
17:45:13: Loading base resource
17:45:14: Base resource loaded
17:45:14: SLADE Initialisation OK
17:45:14: Checking for updates...
17:45:14: Latest stable release: v3110 "3.1.1"
17:45:14: Latest beta release: v3110_b3 "3.1.1 Beta 3"
17:45:14: Already up-to-date
17:45:26: Opening archive E:/Stuff/Games/Doom/psx doom 2oth anniversary soundtrack/ogg/psx20.wad
17:45:38: Warning: No fluidsynth soundfont set, MIDI playback will not work
17:45:38: Opening took 11446 ms
`

When trying to save, this is the last thing that comes up in the console:
`17:50:46: Creating backup E:/Stuff/Games/Doom/psx doom 2oth anniversary soundtrack/ogg/psx20.wad.bak'

Maybe size does have something to do with it? Most of the tracks are between 7 and 14 mb in size. I was able to add 13 of the tracks and save until I tried to insert the 14th. Then started getting the crash. Last time, I was actually able to add the 14th track and save, but then it crashed when trying to save the 15th track. 

Looking at the stack trace, I noticed something. What is
'34: (c:\dev\slade3\src\application\mainapp.cpp:421) WinMain'?

I don't have that file location on my computer. 
`

**Comment by sirjuddington** [comment] 2016-03-07 02:06
Don't have to worry about the filenames on the stack trace, they are the source file locations on my computer (since I built the SLADE.exe file)

I guess it is something size related, possibly when creating the backup. I'm assuming there is enough space left on your `E:` drive to save it? If possible, could you upload the music files somewhere in a zip so I can try this myself?

**Comment by L3gend** [comment] 2016-03-07 02:41
Yeah, there is enought room on the hard drive still.

I could send you the music files, but I don't think I can post them publically since they are the 20th anniversary psx tracks by aubrey hodges. In a private email maybe.

**Comment by sirjuddington** [comment] 2016-03-07 05:02
Yeah send them in an email, would be helpful. Just out of interest, does the same thing happen if you try to do 'Save As' and save it as a new file?

**Comment by Gaerzi** [comment] 2016-03-07 10:55
I mean the start page. Blue background, with SLADE logo on it, and boxes for "Get started", "links", tip of the day", and "recent files", and if you look at the tab's name for it it says "Start Page". Like every tab, you can close it.

For some reason, your stack trace show the crash happening in a function that only happens when the start page is the active tab.

**Comment by L3gend** [comment] 2016-03-08 02:55
what email do I send it to?

**Comment by sirjuddington** [comment] 2016-03-08 03:01
sirjuddington at gmail.com

**Comment by L3gend** [comment] 2016-03-08 03:03
I just tried again and closed the start page like gaerzi suggested. I was able to get the 15th track saved, but then when trying to add another, it crashed again. This time it did not give me a stack trace though.

**Comment by L3gend** [comment] 2016-03-08 03:59
email sent

**Comment by sirjuddington** [comment] 2016-03-08 12:34
Ok this should be fixed in the next release - it's due to SLADE trying to allocate the whole ~200mb of memory for the wad file at once, which can fail fairly easily in 32bit Windows with limited RAM.

**Closed** 2016-03-08 12:35 UTC
Labels: crash bug
