### ISSUE TITLE
Tried to set sector floor height to the ceiling height (128), immediately crashed

### ISSUE THREAD

**Issue by extremelygeneriusername** [sirjuddington/SLADE#1528] opened 2023-06-11 18:31 UTC
**SLADE Version**: (3.2.3 64x)
**Operating System**: (Windows)

**Issue Details**:
Version: 3.2.3 (x64)
Current action: mapw_item_properties
Operating System: Windows 10 (build 19045), 64-bit edition
Graphics Vendor: NVIDIA Corporation
Graphics Hardware: NVIDIA GeForce GT 635/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 471.41

Stack Trace:
0: [unknown location] [unknown:3148255433]
1: [unknown location] [unknown:3148458840]
2: [unknown location] [unknown:3147972562]
3: [unknown location] [unknown:3147800237]
4: [unknown location] [unknown:3147945929]
5: [unknown location] [unknown:3143244372]
6: [unknown location] [unknown:3142547190]
7: [unknown location] [unknown:3152211124]
8: [unknown location] [unknown:3152376495]
9: [unknown location] [unknown:3152379395]
10: [unknown location] [unknown:3152380257]
11: [unknown location] [unknown:3152376282]
12: [unknown location] [unknown:3152380190]
13: [unknown location] [unknown:3153405091]
14: [unknown location] [unknown:3152376364]
15: [unknown location] [unknown:3152379242]
16: [unknown location] [unknown:3153902821]
17: [unknown location] [unknown:3154201177]
18: [unknown location] [unknown:3153431830]
19: [unknown location] [unknown:3154655919]
20: [unknown location] [unknown:3154657808]
21: [unknown location] [unknown:3153499861]
22: [unknown location] CallWindowProcW
23: [unknown location] DispatchMessageW
24: [unknown location] [unknown:3153421377]
25: [unknown location] [unknown:3153393574]
26: [unknown location] [unknown:3147975454]
27: [unknown location] [unknown:3147842096]
28: [unknown location] [unknown:3148300282]
29: [unknown location] [unknown:3152211124]
30: [unknown location] [unknown:3152376495]
31: [unknown location] [unknown:3152379395]
32: [unknown location] [unknown:3152380257]
33: [unknown location] [unknown:3152376282]
34: [unknown location] [unknown:3152379242]
35: [unknown location] [unknown:3153437603]
36: [unknown location] [unknown:3153464051]
37: [unknown location] [unknown:3153474696]
38: [unknown location] [unknown:3153499861]
39: [unknown location] CallWindowProcW
40: [unknown location] CallWindowProcW
41: [unknown location] glPushClientAttrib
42: [unknown location] CallWindowProcW
43: [unknown location] CallWindowProcW
44: [unknown location] [unknown:3151815201]
45: [unknown location] CallWindowProcW
46: [unknown location] DispatchMessageW
47: [unknown location] [unknown:3154805932]
48: [unknown location] [unknown:3152863747]
49: [unknown location] [unknown:3152864282]
50: [unknown location] [unknown:3152216599]
51: [unknown location] [unknown:3152902076]
52: [unknown location] [unknown:3152365192]
53: [unknown location] [unknown:3157196510]
54: [unknown location] BaseThreadInitThunk
55: [unknown location] RtlUserThreadStart

Last Log Messages:
Can't convert "lineid" to an integer (invalid)
Initialising OpenGL...
OpenGL Version: 4.6
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening map map01
Removed 0 detached vertices, 0 detached sides, 0 invalid sides and 0 detached sectors

**Comment by PerdGateEnjoyer** [comment] 2023-06-12 06:51
cool

**Comment by sirjuddington** [comment] 2023-06-21 07:33
Duplicate of #1512 (fixed for next release)

**Closed by sirjuddington** 2023-06-21 07:33 UTC
