### ISSUE TITLE
Make auto-align handle texture scaling

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#850] opened 2018-02-17 21:49 UTC
While working in a scaling-heavy map project, I've noticed that ctrl+a does set the offsets properly... for 1x scaling, when the walls have 2x.

I was wondering if it's possible to make this scaling-aware.

**Comment by sirjuddington** [comment] 2022-03-28 11:46
This one is a duplicate of #399

**Closed by sirjuddington** 2022-03-28 11:46 UTC
Labels: map editor, enhancement
