### ISSUE TITLE
Opening Texture1 and slade crashes

### ISSUE THREAD

**Issue by RishiSlop** [sirjuddington/SLADE#1701] opened 2024-07-22 01:28 UTC
### SLADE Version

3.2.6

### OS

Linux

### Editor

Resource editor

### Steps to Reproduce

Open doom2.wad

Double click texture1 

sorry bad english

### Crash Information

```text
Version: 3.2.6
No current action

Operating System: Linux 5.15.0-91-generic x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:

Last Log Messages:
Loading text style sets
Loading colour configuration
Loading base resource
Base resource loaded
Loading game configurations
SLADE Initialisation OK
Opening archive /home/winterpol/Desktop/Ethos/Gog/Doom/Iwads/DOOM2.WAD
Opening took 86 ms
Setting up the OpenGL context
Failed to setup the OpenGL context
```

**Comment by Blzut3** [comment] 2024-07-22 02:30
Ultimately probably duplicate of #1672.

**Closed** 2024-07-22 11:30 UTC
Labels: crash bug
