### ISSUE TITLE
SLADE Crashes when trying to copy TEXTURE entries between PWADs.

### ISSUE THREAD

**Issue by saski4711** [sirjuddington/SLADE#1013] opened 2019-01-04 12:06 UTC
**SLADE Version**: (git head)
**Operating System**: (Linux)

**Issue Details**:
SLADE Crashes when trying to copy TEXTURE entries between PWADs.
Reproduce by copying emtry from one pwas to another. Crashes upon paste action.
Trace:
Version: 3.2.0 beta 1
No current action

Operating System: Linux 4.20.0-drmtip+ x86_64
Graphics Vendor: Intel Open Source Technology Center
Graphics Hardware: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL Version: 4.3 (Compatibility Profile) Mesa 18.3.1

Stack Trace:
0: [unknown location] [unknown:1099219072]
1: [unknown location] [unknown:1062287392]
2: [unknown location] Announcer::announce(wxString const&)
3: [unknown location] PatchTable::addPatch(wxString const&, bool)
4: [unknown location] TextureXPanel::paste()
5: [unknown location] TextureXPanel::onTextureListKeyDown(wxKeyEvent&)
6: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
7: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
8: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
9: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
10: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
11: [unknown location] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
12: [unknown location] [unknown:1103430794]
13: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
14: [unknown location] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
15: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
16: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
17: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
18: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
19: [unknown location] [unknown:1103319931]
20: [unknown location] [unknown:1081078891]
21: [unknown location] g_closure_invoke
22: [unknown location] [unknown:1070414131]
23: [unknown location] g_signal_emit_valist
24: [unknown location] g_signal_emit
25: [unknown location] [unknown:1080745764]
26: [unknown location] gtk_window_propagate_key_event
27: [unknown location] [unknown:1103241512]
28: [unknown location] [unknown:1081078891]
29: [unknown location] g_closure_invoke
30: [unknown location] [unknown:1070414131]
31: [unknown location] g_signal_emit_valist
32: [unknown location] g_signal_emit
33: [unknown location] [unknown:1080745764]
34: [unknown location] [unknown:1079443009]
35: [unknown location] gtk_main_do_event
36: [unknown location] [unknown:1076549797]
37: [unknown location] [unknown:1076748466]
38: [unknown location] g_main_context_dispatch
39: [unknown location] [unknown:1069411448]
40: [unknown location] g_main_loop_run
41: [unknown location] gtk_main
42: [unknown location] wxGUIEventLoop::DoRun()
43: [unknown location] wxEventLoopBase::Run()
44: [unknown location] wxAppConsoleBase::MainLoop()
45: [unknown location] wxEntry(int&, wchar_t**)
46: [unknown location] main
47: [unknown location] __libc_start_main
48: [unknown location] _start

Last Log Messages:
Initialising OpenGL...
OpenGL Version: 4.3
Max Texture Size: 16384x16384
Checking extensions...
Vertex Buffer Objects supported
Point Sprites supported
Framebuffer Objects supported
Opening archive /opt/source/wadsav/d2-361.wad
Error Parsing ZMapInfo: Expecting "{", got "map01" at line 1
Opening took 283 ms

**Comment by sirjuddington** [comment] 2019-11-04 21:23
Closing this one, I can't reproduce it in the latest master so assuming it was fixed, if it still happens feel free to reopen the issue

**Closed by sirjuddington** 2019-11-04 21:23 UTC
Labels: crash bug
