### ISSUE TITLE
Problems with the latest version on Mac

### ISSUE THREAD

**Issue by kulesh0ff** [sirjuddington/SLADE#1071] opened 2019-09-05 16:39 UTC
**SLADE Version**: 3.1.6
**Operating System**: macOS Mojave

**Issue Details**:
Unfortunately, the latest version is absolutely not working on the Mac. If in the previous one there were a lot of glitches, but it was fashionable to live with them (for example, in 3D mode, when you turn the camera right or left, it simultaneously turns up, regardless of whether you use a trackpad or mouse), then in the latter, when you switch to 3D mode, the camera starts uninterrupted rotate ... Removed and set 3.1.3. :(

**Comment by JadingTsunami** [comment] 2019-10-06 18:47
Try the instructions in #1048

**Comment by sirjuddington** [comment] 2019-11-11 07:13
Closing as a duplicate of #1048

**Closed by sirjuddington** 2019-11-11 07:13 UTC
