### ISSUE TITLE
Crashing when creating map.

### ISSUE THREAD

**Issue by Debi-sys** [sirjuddington/SLADE#1370] opened 2022-05-08 00:19 UTC
Version: 3.2.0
No current action

Operating System: Linux 5.17.5-arch1-1 x86_64
Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

Stack Trace:
0: [unknown location] [unknown:139681862121542]
1: [unknown location] [unknown:139681751267212]
2: [unknown location] [unknown:139681843541344]
3: [unknown location] XQueryExtension
4: [unknown location] [unknown:139681858862216]
5: [unknown location] glXQueryVersion
6: [unknown location] wxGLCanvasX11::GetGLXVersion()
7: [unknown location] wxGLContext::wxGLContext(wxGLCanvas*, wxGLContext const*)
8: [unknown location] slade::gl::getContext(wxGLCanvas*)
9: [unknown location] slade::OGLCanvas::setActive()
10: [unknown location] slade::MapEditContext::forceRefreshRenderer()
11: [unknown location] slade::MapEditorWindow::forceRefresh(bool) const
12: [unknown location] slade::MapTextureManager::refreshResources()
13: [unknown location] slade::MapEditorWindow::openMap(slade::Archive::MapDesc)
14: [unknown location] slade::MapEditorWindow::chooseMap(slade::Archive*)
15: [unknown location] slade::ArchiveManagerPanel::handleAction(std::basic_string_view<char, std::char_traits<char> >)
16: [unknown location] slade::SActionHandler::doAction(std::basic_string_view<char, std::char_traits<char> >)
17: [unknown location] slade::SStartPage::onHTMLLinkClicked(wxEvent&)
18: [unknown location] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
19: [unknown location] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
20: [unknown location] wxEvtHandler::TryHereOnly(wxEvent&)
21: [unknown location] wxEvtHandler::ProcessEventLocally(wxEvent&)
22: [unknown location] wxEvtHandler::ProcessEvent(wxEvent&)
23: [unknown location] wxEvtHandler::SafelyProcessEvent(wxEvent&)
24: [unknown location] [unknown:139681871363925]
25: [unknown location] [unknown:139681759425846]
26: [unknown location] [unknown:139681759412279]
27: [unknown location] g_cclosure_marshal_generic
28: [unknown location] g_closure_invoke
29: [unknown location] [unknown:139681842060200]
30: [unknown location] g_signal_emit_valist
31: [unknown location] g_signal_emit
32: [unknown location] [unknown:139681793350385]
33: [unknown location] [unknown:139681823726573]
34: [unknown location] [unknown:139681792739205]
35: [unknown location] [unknown:139681822510352]
36: [unknown location] [unknown:139681790407303]
37: [unknown location] [unknown:139681792378544]
38: [unknown location] [unknown:139681792846746]
39: [unknown location] [unknown:139681792338334]
40: [unknown location] [unknown:139681792342668]
41: [unknown location] [unknown:139681751372538]
42: [unknown location] [unknown:139681751496582]
43: [unknown location] g_main_context_dispatch
44: [unknown location] [unknown:139681836292585]
45: [unknown location] g_main_loop_run
46: [unknown location] gtk_main
47: [unknown location] wxGUIEventLoop::DoRun()
48: [unknown location] wxEventLoopBase::Run()
49: [unknown location] wxAppConsoleBase::MainLoop()
50: [unknown location] wxEntry(int&, wchar_t**)
51: [unknown location] main
52: [unknown location] [unknown:139681843454736]
53: [unknown location] __libc_start_main
54: [unknown location] _start

Last Log Messages:
Can't convert "ceiling_lowerbytexture" to an integer (invalid)
Can't convert "stairs_builddowndoom" to an integer (invalid)
Can't convert "stairs_buildupdoomsync" to an integer (invalid)
Can't convert "stairs_builddowndoomsync" to an integer (invalid)
Can't convert "polyobj_startline" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Can't convert "lineid" to an integer (invalid)
Setting up the OpenGL context

**Comment by FlykeSpice** [comment] 2022-05-13 19:37
I can't reproduce this issue on my Manjaro 21.2.6 Qonos with slade 3.2.1, from the stack trace the crash is happening outside SLADE, when attempting to create the Opengl context.

It's not SLADE's fault, there is an issue with your Opengl driver, you can see right away on the very first lines:

> Graphics Vendor: OpenGL not initialised
Graphics Hardware: OpenGL not initialised
OpenGL Version: OpenGL not initialised

**Comment by FlykeSpice** [comment] 2022-05-14 16:01
Ok, so I searching further  this seems related to wxWidgets not working with Wayland (which seems you are using), see: https://github.com/wxWidgets/wxWidgets/issues/17702 many users have reported having very similar crash log as yours.

However the fix has been upstreamed already 2 years ago so you probably using slade built against an older version of wxWidgets, Either you compiled it youself with a old version wxWidget package or slade official binaries were built with an old version.

@sirjuddington ?

**Comment by FlykeSpice** [comment] 2022-05-14 22:43
Oh wait, you must have installed from the Arch Linux packages, which dynamically links to whatever wxwidgets package version is currently installed in your system, which in the official repositories is still **3.0.5,** the same 2 year old version that precedes the upstreamed fixes :skull:

You should ask the package maintainers to update it or install it from the AUR repositories which is updated to lastest versions.

**Comment by SteelTitanium** [comment] 2022-05-15 18:09
> Oh wait, you must have installed from the Arch Linux packages, which dynamically links to whatever wxwidgets package version is currently installed in your system, which in the official repositories is still **3.0.5,** the same 2 year old version that precedes the upstreamed fixes skull
> 
> You should ask the package maintainers to update it or install from the AUR repositories which is updated to lastest versions.

It's still 3.0.5 because that IS the last stable version of wxWidgets that was released. And it wouldn't make sense to push in-dev versions to the main repos.

**Comment by FlykeSpice** [comment] 2022-05-16 00:39
Yeah, I just checked that, and also 3.1.x breaks api compatibility, my bad. Though SLADE already includes some code that deals with wx 3.1.x compatibility (e067f45f6c08d43d831ed0360a05eff1f572c901).

The main point is this isn't SLADE's issue but wxWidget 3.0.5 is broken in Wayland.

SLADE 3.3.x , which is now in development, will require wx 3.1.0+ (2a3f94aaee9fb5c181b525f7cb2a589d8e39ed8d), OP will have to wait for a while.

Or can try this workaround in 3.0.5:
`GDK_BACKEND=x11 slade`

**Closed** 2023-06-04 08:41 UTC
Labels: linux, crash bug, platform issue
