### ISSUE TITLE
slade not opening mac os Sonoma

### ISSUE THREAD

**Issue by tyhomas** [sirjuddington/SLADE#1623] opened 2023-12-10 11:00 UTC
**SLADE Version**: (3.1.1.5)
**Operating System**: (OSX)

**Issue Details**:
every time I open Slade on mac os Sonoma, it crashes.

**Comment by prenaux** [comment] 2023-12-15 16:45
I have Sonoma and it works ok here. I have v3.1.6 that I downloaded from the website.

The issues I have are a) it doesnt work correctly in dark mode, b) if you dont give it "Accessibility" rights in Privacy&Security the 3D view mouse capture doesnt work and it just spins.

I encountered the second because I much prefer to start from the cmd line, but alas I cant find a way to give it those rights that way, so I have to start it from Finder :(

**Comment by sirjuddington** [comment] 2023-12-19 07:11
Closing this as a duplicate of #1613

**Closed by sirjuddington** 2023-12-19 07:11 UTC
Labels: macos
